### ISSUE TITLE
OpenComputers support for AE2FC components

### ISSUE THREAD

**Issue by DaComputerNerd717** [GlodBlock/AE2FluidCraft-Rework#101]
AE2 has for some time had an OpenComputers API, providing [components for the interface, export bus, and import bus](https://ocdoc.cil.li/component:applied_energistics)). I was quite disappointed to see that the same is not done for the dual interfaces in this mod. Can this be added?

**Comment by DaComputerNerd717** [comment]
The good news is at least, when using dual interfaces, the OpenComputers ME Controller API lets you craft any dual recipe in the ME system successfully, so a workaround for the export bus controls is to have a recipe programmed that actually doesn't make the thing, just to get the fluid exported by starting the craft, waiting a moment, and cancelling it

**Comment by GlodBlock** [comment]
you mean the 1.7.10 one or 1.12.2 one?

**Comment by DaComputerNerd717** [comment]
1.12, I haven't even checked if it's there in 1.7 or not

**Comment by GlodBlock** [comment]
added in 2.4.25-r https://legacy.curseforge.com/minecraft/mc-mods/ae2-fluid-crafting-rework/files/4664933
