### ISSUE TITLE
Three problems regarding fluid pattern terminal

### ISSUE THREAD

**Issue by YiRanMushroom** [GlodBlock/AE2FluidCraft-Rework#103]
1. A fluid pattern cannot be recasting into a regular pattern even if the fluid was removed from it. You can make a new one it's totally fine but you cannot directly cast the fluid pattern into a regular pattern if in the result slot of the terminal.
2. Auto stack method cannot practically work. Even with the function on, jei auto fill can only recognize first 9/16 objects and try to stack them. For example, if I need to use 25 obsidian to make a compress obsidian in a extended crafting table, which takes 25 slots separately, It can only fill 16. So if a recipe take over 16 slots but can fit in a pattern(its kinds are less than 16), it cannot fill correctly.
3. Fluid pattern encode terminal sometimes cannot choose the existing item in ME or cannot auto fill the object whose pattern exists in ME. Especially for those in a crafting pattern(in stead of a processing pattern)

**Comment by GlodBlock** [comment]
> 3\. Fluid pattern encode terminal sometimes cannot choose the existing item in ME or cannot auto fill the object whose pattern exists in ME. Especially for those in a crafting pattern(in stead of a processing pattern)

这个是指什么，你用中文描述一下，如果有截图最好

**Comment by YiRanMushroom** [comment]
流体样板终端使用jei填充不能正确识别配方中可替换的物品。通常情况下，一般的样板终端会优先填充有合成方式的物品，和ME中已经存在的物品。比如用八个木板合成一个箱子，一般的样板终端会识别网络中已存在的木板，而流体样板终端却有时无法识别这样的物品。
这个问题以前也有，后来修复了，但是AE2之后又改变了合成终端中自动填充的算法，现在出现这个问题可能与这个有关。

**Comment by GlodBlock** [comment]
![QQ录屏20230729100911](https://github.com/GlodBlock/AE2FluidCraft-Rework/assets/60341015/62a62bad-0ce1-4efa-978e-a55dc8023de4)
这个应该是没有问题的
