### ISSUE TITLE
ME Extended Processing Fluid Pattern Terminal question

### ISSUE THREAD

**Issue by OnlySole-IN** [GlodBlock/AE2FluidCraft-Rework#104]
Why the game didn't respond when I added the fluid recipe for GTCEu

And there was no misstatement

**Comment by GlodBlock** [comment]
有崩溃报告吗

**Comment by OnlySole-IN** [comment]
没有

**Comment by OnlySole-IN** [comment]
只有长时间的未响应

**Comment by GlodBlock** [comment]
那把logs文件夹下的latest.log发一下

**Comment by OnlySole-IN** [comment]
[latest.log](https://github.com/GlodBlock/AE2FluidCraft-Rework/files/12213658/latest.log)

**Comment by GlodBlock** [comment]
2.4.27已修复https://github.com/GlodBlock/AE2FluidCraft-Rework/releases/tag/2.4.27-r
