### ISSUE TITLE
[1.16.5] Terminal cannot perserve user configurations

### ISSUE THREAD

**Issue by ZZZank** [GlodBlock/AE2FluidCraft-Rework#106]
Every time I switch to Terminal GUI, whether through clicking terminal to open it or through going back from other GUI, those configurations will be reset: 
![Clip_20230803_163739.png](https://github.com/GlodBlock/AE2FluidCraft-Rework/assets/47418975/cbf1517e-1aaa-4efd-ad58-98f884ff026f)

**Comment by GlodBlock** [comment]
fixed in 1.0.1 https://github.com/GlodBlock/AE2FluidCraft-Rework/releases/tag/1.0.1-a
