### ISSUE TITLE
[1.16.5] Lag spike when opening Terminal

### ISSUE THREAD

**Issue by ZZZank** [GlodBlock/AE2FluidCraft-Rework#107]
When opening Fluid Pattern Terminal, there will be an apparent lag, which did not exist on AE's terminals: 

https://github.com/GlodBlock/AE2FluidCraft-Rework/assets/47418975/b7c60bc8-e69b-4061-b9d1-aa21b9bc1b6c

**Comment by GlodBlock** [comment]
that lag seems comes from the items in pattern slots, the normal pattern terminal also lags when there are items in its pattern pattern slots

**Comment by ZZZank** [comment]
Over the last few days, I've tested this lag on multiple MC instances, and found that such lag is more noticeable on larger packs, like  [Enlightened6Expert](https://www.curseforge.com/minecraft/modpacks/enlightened-6) , and barely noticieable on smaller ones, like a small pack involving only 7 major mods. 

In general, the lag will become more severe as the modlist grows, but in any circumstances, the lag of Fluid Pattern Terminal is sharper than the one of AE's Pattern Terminal. 

Even when I compare `AE2FC one with no item inside pattern slot` against `AE one with many items inside pattern slot` , the AE2FC one still lags more. 

Maybe there's some design problems. Or if this is 'working as expected', feel free to close this issue.

**Comment by GlodBlock** [comment]
这个是ae2的毛病，如果当前样板格子上的不是合法的合成配方，它就会一直查询配方然后卡，普通样板终端也是一样的。
我修只能修我这里的终端

**Comment by GlodBlock** [comment]
已修复https://github.com/GlodBlock/AE2FluidCraft-Rework/releases/tag/1.0.2-a
