### ISSUE TITLE
JEI 只能填充 16 种物品/流体

### ISSUE THREAD

**Issue by ghost** [GlodBlock/AE2FluidCraft-Rework#112]
测试配方
![image](https://github.com/GlodBlock/AE2FluidCraft-Rework/assets/103164772/d6256e01-edc1-4c06-8210-ce5b5de119ba)

填充结果
![image](https://github.com/GlodBlock/AE2FluidCraft-Rework/assets/103164772/e66a6ef7-224c-4aaa-812b-fb6878103f7b)

**Comment by GlodBlock** [comment]
怎么会是呢

**Comment by GlodBlock** [comment]
已修复https://github.com/GlodBlock/AE2FluidCraft-Rework/releases/tag/2.4.31-r
