### ISSUE TITLE
想问一下:有没有可能提供一下mek的气体合成？

### ISSUE THREAD

**Issue by zeng-github01** [GlodBlock/AE2FluidCraft-Rework#115]
以及类似三合一接口之类的，可以作为一个新的Mod作为Aeadditions的附属

或者是内部集成 检测一下AEadditions是否安装。安装后加载相应的模块

**Comment by zeng-github01** [comment]
三合一接口可以用Mod集成的形式检测ae2fcr，如果安装了再加载三合一，否则就用正常的二合一气体接口，算是不错的主意

不过这种方案通常是用独立mod做

**Comment by GlodBlock** [comment]
这个东西搞起来比较麻烦，等我明年考完研在做

**Comment by zeng-github01** [comment]
加油作者！不过这个应该和液体合成是同一个框架的mod吧，可以改改测试一下

**Comment by zeng-github01** [comment]
@GlodBlock 我看了Aeadditions的源码，它的气体是基于IAEFluid的对象制作的，集成难度看起来不会很难，只需要做一下运行时对象做兼容就可以了

看这个情况，还是将气体模块集成到这个mod更好一点

**Comment by zeng-github01** [comment]
@GlodBlock 个人认为这个请求的令人纠结的部分是：如何给气体提供一个图标？作者你怎么看

**Comment by GlodBlock** [comment]
你指哪里的图标，液滴那种吗

**Comment by zeng-github01** [comment]
> 你指哪里的图标，液滴那种吗

没错，绞尽脑汁都想不出气体图标应该长啥样...
顺便，我本地已经在尝试沿着现有架构实现这个请求。目前已经将所有Mek气体添加到创造物品栏 目前暂时命名为气体液滴。毕竟实在不知道该叫个什么名字，以及用一个什么图标
![image](https://github.com/GlodBlock/AE2FluidCraft-Rework/assets/95841646/72f96ec7-7c0b-42f4-9715-1069e05db235)


额外吐槽：自己实现自己的请求总觉得怪怪的。顺便使用的Mek版本是社区版，所以有反物质啥的

@GlodBlock 至于图标，只能仰赖作者大大了。 目前是加了Mod检测，没有mek这些气体液滴就不加载。减少耦合。至于这些气体液滴为啥全导入了，因为这个只对外开放了一个List

**Comment by GlodBlock** [comment]
图标就直接倒置的液滴，等我25号之后再来写

**Comment by zeng-github01** [comment]
> 图标就直接倒置的液滴，等我25号之后再来写

哇靠，我怎么就没想到呢，液体向下滴落，气体不就是向上逃逸嘛。

**Comment by zeng-github01** [comment]
@GlodBlock  目前已经阶段性的进行了集成，提交在这里： [提交](https://github.com/zeng-github01/AE2FluidCraft-Rework/commit/67b1c763eec29e39f7890f10f801079fc4bc6e06)

但是TileFluidDiscretizer 这个Tile 不好改，为了解耦合，我个人认为还是把这两个块和对应的Tile 分开。

查了一下这个是流体离散器，干脆弄个气体离散器，把材质涂黄就可以了。(本地)目前已经创建了两个个空的框架类，还没写逻辑。

(本地)想了一下，气体液滴改成气滴好了，气体液滴总觉得怪怪的

**Comment by GlodBlock** [comment]
主要问题是在接口发配材料上，离散器问题不是很大，液滴和封包的代码我准备重构了，给假物品注册一个handler来进行解包封包，而不是直接放Item类里

**Comment by zeng-github01** [comment]
> 主要问题是在接口发配材料上，离散器问题不是很大，液滴和封包的代码我准备重构了，给假物品注册一个handler来进行解包封包，而不是直接放Item类里

那我干脆先PR合并现有代码？
其他的就由作者大大来折腾

**Comment by GlodBlock** [comment]
这个就不用了，都我来写

**Comment by GlodBlock** [comment]
已添加 https://github.com/GlodBlock/AE2FluidCraft-Rework/commit/2d9c135f81884b37f51e8ab4a30c9c5d5b6b0b38
