### ISSUE TITLE
1.12.2 - Add wireless a fluid pattern terminal (Extended also.)

### ISSUE THREAD

**Issue by Micaias32** [GlodBlock/AE2FluidCraft-Rework#117]
The idea would be to have a terminal like the one in GTNH.
Also maybe a universal one with all the terminals on it.
The problem with that it would mean to add the interface (maybe fluid interface too) before the uni terminal.

**Comment by zeng-github01** [comment]
@GlodBlock Please notify me when this issue is completed and I will modify Aeadditions' Universal terminal to support the terminal in this issue

请在这个issue完成时通知我(@)，我将对Aeadditions的统一终端进行修改，让它支持这个issue中的终端。

或者大佬你可以自己改一下我的分支，或者至少弄个打开终端的接口

**Comment by GlodBlock** [comment]
added in https://github.com/GlodBlock/AE2FluidCraft-Rework/commit/c96b684cac98bacb612ad2036bdc9a76d4fe2a73
the extended one can't be done due to ae2 itself limitations.
@zeng-github01 已添加
