### ISSUE TITLE
[BUG] 终极编码台使用不当会导致崩溃。

### ISSUE THREAD

**Issue by KasumiNova** [GlodBlock/AE2FluidCraft-Rework#118]
转移某些 JEI 槽位总数大于 16 的物品后，**发配合成任务将会 100% 导致游戏崩溃**。

复现示例（不限于以下配方，只要超过 16 槽位就会崩溃）：
![0fb6bc8e76cf15be2e375d3f4b1bcfc3](https://github.com/GlodBlock/AE2FluidCraft-Rework/assets/48862050/d25f0a8e-affc-4fa3-bf29-b82a13763a23)

相关日志：https://mclo.gs/6GlxPUq
模组版本：2.4.31-r

**Comment by GlodBlock** [comment]
已修复 https://github.com/GlodBlock/AE2FluidCraft-Rework/releases/tag/2.4.32-r
