### ISSUE TITLE
ME Fluid Assembler PAE2 BUG GUI

### ISSUE THREAD

**Issue by NuanKi** [GlodBlock/AE2FluidCraft-Rework#122]
The GUI of the Assembler is bugged, it doesnt accept patterns, and in the upgrade slots you can put whatever you want
![image](https://github.com/GlodBlock/AE2FluidCraft-Rework/assets/80914838/19f40c58-72d3-444e-8be7-283331e54296)
and the 3x3 acts like a pattern terminal in the way that you can set "ghost items" for the patterns
![image](https://github.com/GlodBlock/AE2FluidCraft-Rework/assets/80914838/43ec48a8-5973-4a7d-b6ca-ef0a27486f80)

**Comment by GlodBlock** [comment]
fluid assembler only accept fluid pattern (the dark blue one)
![image](https://github.com/GlodBlock/AE2FluidCraft-Rework/assets/60341015/756fc8e0-06f2-4bbc-8027-7f7b909f0ae8)
you get it by clicking the encode button on fluid pattern terminal
![image](https://github.com/GlodBlock/AE2FluidCraft-Rework/assets/60341015/482db4ec-9a25-4d90-ad36-7439bffab8b1)
the normal crafting pattern won't be accepted

other issues will be fixed later

**Comment by GlodBlock** [comment]
fixed in 2.4.33 https://github.com/GlodBlock/AE2FluidCraft-Rework/releases/tag/2.4.33-r

**Comment by NuanKi** [comment]
thank you, that helped a lot, but i found another problem
![image](https://github.com/GlodBlock/AE2FluidCraft-Rework/assets/80914838/388d60a6-d116-46a0-b07b-ab33bc8f921e)
i activated the oredict substitutions since it doesnt matter what type of wood i use for this 
but it seems like the fluid patterns cant substitute a element
![image](https://github.com/GlodBlock/AE2FluidCraft-Rework/assets/80914838/6a99aa80-8caa-4f23-b4e3-223a4fe5b273)
![image](https://github.com/GlodBlock/AE2FluidCraft-Rework/assets/80914838/21f21cd2-b922-48f8-b3a8-33a9ab6ebca1)
while when using the normal one allows the substitution

**Comment by NuanKi** [comment]
<3 Thank You for that
