### ISSUE TITLE
Patterns cant use the Ore-dict substitution function

### ISSUE THREAD

**Issue by NuanKi** [GlodBlock/AE2FluidCraft-Rework#123]
thank you, that helped a lot, but i found another problem
![image](https://github.com/GlodBlock/AE2FluidCraft-Rework/assets/80914838/388d60a6-d116-46a0-b07b-ab33bc8f921e)
i activated the oredict substitutions since it doesnt matter what type of wood i use for this 
but it seems like the fluid patterns cant substitute a element
![image](https://github.com/GlodBlock/AE2FluidCraft-Rework/assets/80914838/6a99aa80-8caa-4f23-b4e3-223a4fe5b273)
![image](https://github.com/GlodBlock/AE2FluidCraft-Rework/assets/80914838/21f21cd2-b922-48f8-b3a8-33a9ab6ebca1)
while when using the normal one allows the substitution
![image](https://user-images.githubusercontent.com/80914838/280626509-566ae037-3ffe-43c0-bc55-d44f771d1526.png)

**Comment by GlodBlock** [comment]
yea the fluid assembler doesn't support substitution for now since it is bit complex to implemente.
i don't have much time recently so i only do bugfix now. i will work on these feature request in next year

**Comment by NuanKi** [comment]
sure, np, tysm for everything
i guess i will simply create the pattern with the wood i have the most :D

**Comment by YiRanMushroom** [comment]
You should never use oreDict substotution, AE2 often have problems about that

**Comment by NuanKi** [comment]
> You should never use oreDict substotution, AE2 often have problems about that

It was possibly the case with the old ae2 but with ae2 extended life its not

**Comment by GlodBlock** [comment]
well after further investigation, it can't be done on my addon side. the substitution mode is hard coded on ae2 side and i can't do anything about it

**Comment by zeng-github01** [comment]
> well after further investigation, it can't be done on my addon side. the substitution mode is hard coded on ae2 side and i can't do anything about it

How is it coded?
