### ISSUE TITLE
Add subnet blocking mode support for dual interfaces.

### ISSUE THREAD

**Issue by CactusCool** [GlodBlock/AE2FluidCraft-Rework#125]
AE2 uel adds support for full network blocking mode on regular interfaces. this means that if there is any item detected on the network it wont push items. This unfortunately does not work with dual interfaces meaning you have to use regular interfaces sending fluid packets that you then have to decode. If dual interfaces could be changed to respect blocking mode with fluids anywhere in the subnet ae2 can see it would be a huge benefit for automation setups. something similar to this is the gtnh adv blocking cards that works with fluids or items on subnets. Having this in 1.12 would be really nice as well.

**Comment by GlodBlock** [comment]
this feature is actually duplicate with https://github.com/GlodBlock/AE2FluidCraft-Rework/issues/116
