### ISSUE TITLE
部分方块渲染错误

### ISSUE THREAD

**Issue by zeng-github01** [GlodBlock/AE2FluidCraft-Rework#126]
流体缓存指令器应该对应的懒人AE2的缓存指令器，但是方块的正面永远是朝上的。希望能修复这个问题

**Comment by GlodBlock** [comment]
mc的那个blockstate我也不太清楚怎么用，之前试图修过但没弄好

**Comment by zeng-github01** [comment]
> mc的那个blockstate我也不太清楚怎么用，之前试图修过但没弄好

抄一下懒人AE2试一下？我简单看一下

回头尝试给这个打个补丁

作者打算单独弄一个气体的版本还是和流体的合到一起

**Comment by zeng-github01** [comment]
> mc的那个blockstate我也不太清楚怎么用，之前试图修过但没弄好

这个确实相当难修，还没懂他们相互之间的连接。弃坑。实在是找不到，各种异常。目前只能把证明调整一下，但是它不会随着玩家视角变化

各种骚操作全都试过了，最好的情况下是不能显示材质 一设置朝向 材质都丢

估计是丢失了json上的model

**Comment by zeng-github01** [comment]
能找到的所有实现都会造成渲染材质丢失，但是又不知道什么原因@GlodBlock

**Comment by GlodBlock** [comment]
所以我说我不知道它是怎么个事，之前修过修不了

**Comment by zeng-github01** [comment]
> 所以我说我不知道它是怎么个事，之前修过修不了

合理推测应该是有配置写错了，我今天仔细看看或者作者你来

代码层面应该是对的，所有有这个功能的模组都是这么实现的。只能看是不是配置错误。@GlodBlock

**Comment by zeng-github01** [comment]
@GlodBlock 该错误对应补丁已提交，转向功能参考原版熔炉，后期可能会改为发射器。我的猜测没错，state的json没写好，添加转向后会丢失模型model参数，导致丢失纹理，并不是没有转向成功。 提交中有一些未使用的import 是在调试期间留下的。作者可以去掉

这个设备是需要频道的吧？要不要考虑弄个未激活的正面纹理。不过支持这个功能估计又要改很久了

**Comment by zeng-github01** [comment]
至于无线流体合成终端的话，缓一段时间再集成。修这个bug修的头痛。真的头在痛。顺便请作者大大，给点协助，比如打开界面的接口啥的，aea那边是用Kotlin object 做链接的，得先准备点接口

**Comment by zeng-github01** [comment]
@GlodBlock 经过测试，服务器模式转向失败，应该是少了world.isRemote之类的判断了。我再补充提交一下？目前客户端正常

服务端无法转向的问题原因未知，暂时弃坑

**Comment by GlodBlock** [comment]
> 至于无线流体合成终端的话，缓一段时间再集成。修这个bug修的头痛。真的头在痛。顺便请作者大大，给点协助，比如打开界面的接口啥的，aea那边是用Kotlin object 做链接的，得先准备点接口

用Util#public static void openWirelessTerminal(ItemStack item, EnumHand hand, World w, EntityPlayer player, GuiType gui)

**Comment by zeng-github01** [comment]
> > 至于无线流体合成终端的话，缓一段时间再集成。修这个bug修的头痛。真的头在痛。顺便请作者大大，给点协助，比如打开界面的接口啥的，aea那边是用Kotlin object 做链接的，得先准备点接口
> 
> 用Util#public static void openWirelessTerminal(ItemStack item, EnumHand hand, World w, EntityPlayer player, GuiType gui)

走的AE2的接口扩展的吗？

**Comment by zeng-github01** [comment]
@GlodBlock 目前这个issue已经修好了客户端功能。到了服务端以后貌似永远都是北方，就没法转向...要不先合了凑合用？还是再纠结一下。然后再考虑适配一下扳手转向

**Comment by zeng-github01** [comment]
@GlodBlock 目前这个issue已经修好了客户端功能。到了服务端以后貌似永远都是北方，就没法转向...要不先合了凑合用？还是再纠结一下

最新更新：修改了实现方法，以修复服务端问题

**Comment by GlodBlock** [comment]
> > > 至于无线流体合成终端的话，缓一段时间再集成。修这个bug修的头痛。真的头在痛。顺便请作者大大，给点协助，比如打开界面的接口啥的，aea那边是用Kotlin object 做链接的，得先准备点接口
> > 
> > 
> > 用Util#public static void openWirelessTerminal(ItemStack item, EnumHand hand, World w, EntityPlayer player, GuiType gui)
> 
> 走的AE2的接口扩展的吗？

ae自己用的enum，没开接口

**Comment by zeng-github01** [comment]
@GlodBlock 通过测试，双端实现符合预期，请进行代码审查后合并

ps: 奇了怪了，第一版实现的对应代码明明是执行到了的，但实际上在服务端没效果。总算是修好了，实在太操蛋。如果作者以后弄一个未激活的贴图，我可以尝试给它实装上。不过我没找到这个设备申请频道的方法

**Comment by zeng-github01** [comment]
> > > > 至于无线流体合成终端的话，缓一段时间再集成。修这个bug修的头痛。真的头在痛。顺便请作者大大，给点协助，比如打开界面的接口啥的，aea那边是用Kotlin object 做链接的，得先准备点接口
> > > 
> > > 
> > > 用Util#public static void openWirelessTerminal(ItemStack item, EnumHand hand, World w, EntityPlayer player, GuiType gui)
> > 
> > 走的AE2的接口扩展的吗？
> 
> ae自己用的enum，没开接口

意思就是说，可能注册了一个枚举值进去了。毕竟ae默认没有这两个终端
