### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by RedShiftT** [GlodBlock/AE2FluidCraft-Rework#13]
Hello
I broke your mode again heh
Didn't do anything special, have no idea why it broke

Crash report: https://pastebin.com/tzWGxzBZ

**Comment by GlodBlock** [comment]
do you connect it with enderio conduits or something like that?

**Comment by RedShiftT** [comment]
Yes I do, both item and ender fluid conduits. They are connected to ingredient buffer. To dual interface connected only item one.

**Comment by RedShiftT** [comment]
It worked perfectly until I inserted pattern for iron, which was very similar to copper pattern. Iron was ordered by export bus, server died after this.

**Comment by GlodBlock** [comment]
[ae2fc-1.7.10-g0bc3e5b.zip](https://github.com/GlodBlock/AE2FluidCraft-Rework/files/8790890/ae2fc-1.7.10-g0bc3e5b.zip)
try this, it should fix the these wired crash from eio pipes

**Comment by RedShiftT** [comment]
Now I can't join my server although I updated mod both on client and server.

[18:50:40 INFO]: Attempting connection with missing mods [kimagine, ae2fc, fc-dummy] at CLIENT
[18:50:40 INFO]: Rejecting connection CLIENT: [FMLMod:ae2fc{g0bc3e5b}]
[18:50:40 INFO]: Sacrilegum lost connection: Mod rejections [FMLMod:ae2fc{g0bc3e5b}]

Tried to downgrade client mod to previous version, didn't work.
Server didn't complain about "kimagine" and "fc-dummy" before update, I don't have a clue what is it.

**Comment by GlodBlock** [comment]
does it only crash on server?

**Comment by GlodBlock** [comment]
wait, do you update the ae2fc both at server and client side? also make sure the server `config` file is the same as the client one

**Comment by RedShiftT** [comment]
Oooopsie forgot to unzip mod on client :(
Should check it before writing you, I'm sorry about this. .zip and .jar looking the same, didn't noticed

Fix works, it seems server don't crash anymore. Thanks for that
