### ISSUE TITLE
Hello, I have noticed some conflicts between this module and the AE2 Unofficial Extended Life module

### ISSUE THREAD

**Issue by zero0CM** [GlodBlock/AE2FluidCraft-Rework#134]
When ae2fc is present at the same time as the v0.54.19 version of AE2 Unofficial Extended Life, the game crashes on the way to load.
The ae2fc version is 2.5.3-r and the AE2 Unofficial Extended Life version is appliedenergistics2-rv6-stable-7-extended_life-v0.54.19 when I put AE2 Unofficial Extended Life is back to normal when updating to the latest version v0.55.29, and the crash report is attached below: https://mclo.gs/o6Tp4BZ

**Comment by PrototypeTrousers** [comment]
ae2fc simply depends on a feature added by AE2 Unofficial Extended Life on a more recent version.
why are you stuck with v0.54.19 but can use the latest ae2fc

**Comment by zero0CM** [comment]
> ae2fc simply depends on a feature added by AE2 Unofficial Extended Life on a more recent version. why are you stuck with v0.54.19 but can use the latest ae2fc

Because the AE2 Unofficial Extended Life version that comes with the modpack I'm playing is v0.54.19, I didn't know that this version is not the latest version, and it has been replaced with the latest version, and there is no problem at present
