### ISSUE TITLE
crash when order something in the ME (Extended) Fluid Pattern Terminal

### ISSUE THREAD

**Issue by nekitbrush** [GlodBlock/AE2FluidCraft-Rework#138]
AE2FC version: 2.5.5-r
[crash-2024-01-20_16.56.20-client.txt](https://github.com/AE2-UEL/AE2FluidCraft-Rework/files/13998629/crash-2024-01-20_16.56.20-client.txt)

**Comment by serenibyss** [comment]
You need to update AE2UEL to latest version (0.56.2 as of right now)
