### ISSUE TITLE
Client crashes when trying to change the amount of mb of liquid in the craft

### ISSUE THREAD

**Issue by David093** [GlodBlock/AE2FluidCraft-Rework#139]
When trying to change the amount of liquid in mb in the craft, the client crashes before leaving the world or server.
Tested on the server, it did not crash when crashing on the client. Can you tell me what the problem is?
[crash-2024-01-30_21.23.27-client.txt](https://github.com/AE2-UEL/AE2FluidCraft-Rework/files/14103283/crash-2024-01-30_21.23.27-client.txt)

**Comment by serenibyss** [comment]
Please update AE2UEL to latest version (0.56.2), it is required for AE2 Fluid Craft 2.5.5+
