### ISSUE TITLE
1.12.2 Crash

### ISSUE THREAD

**Issue by Manuepolis23** [GlodBlock/AE2FluidCraft-Rework#14]
Hello, I was tryin to search for lamp and I got this error :

[https://pastebin.com/8qDwMbpp](https://pastebin.com/8qDwMbpp)

**Comment by GlodBlock** [comment]
i forget the gtce 😵

**Comment by GlodBlock** [comment]
fixed now https://github.com/GlodBlock/AE2FluidCraft-Rework/commit/808196f3c0822dfd457d7612669839f61ff7004b
