### ISSUE TITLE
Client disconnect from server when renaming dual interface

### ISSUE THREAD

**Issue by 3jlowes** [GlodBlock/AE2FluidCraft-Rework#140]
When attempting to name a dual interface from the pattern terminal I get 
"A fatal error has occurred, this connection is terminated" on the client

[19:55:31] [Server thread/ERROR] [FML]: There was a critical exception handling a packet on channel ae2fc

full log
[log.txt](https://github.com/AE2-UEL/AE2FluidCraft-Rework/files/14149298/log.txt)

**Comment by GlodBlock** [comment]
it is nh's ae2fc fork, so please post this issue at nh's repo https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues

**Comment by 3jlowes** [comment]
Thanks! wasnt sure where this would go.
