### ISSUE TITLE
The AE2 Unofficial Extended/AE2 UEL-Extended  and AE2 Fluid Crafting Rework caused the game to lag

### ISSUE THREAD

**Issue by SenjumaruShutara** [GlodBlock/AE2FluidCraft-Rework#141]
Can this mod support "AE2 Unofficial Extended"? When the two mods are used together in V2.5.6 and "AE2 Unofficial Extended"V0.4.0.2, the game will be delayed after the single fluid synthesis and cannot be played.
AE2 Fluid Crafting Rework:V 2.5.6-r
AE2 Unofficial Extended/AE2 UEL-Extended :V0.4.0.2
Minecraft:1.12.2
Forge:14.23.5.2860

**Comment by GlodBlock** [comment]
你指这个mod吗https://github.com/beecupbe/ae2uel_extended
ae2fc不支持任何除了[ae2uel](https://www.curseforge.com/minecraft/mc-mods/ae2-extended-life)以外的任何ae，包括extended的那个
