### ISSUE TITLE
Client crash on autocraft in fluid pattern terminal

### ISSUE THREAD

**Issue by Markh3tr** [GlodBlock/AE2FluidCraft-Rework#142]
Whenever you try to order an autocraft from the fluid pattern terminal your client crashes and gets kicked from the server.
This has something to do with the new ability to use math expressions in the order amount in the newest versions of AE2UEL.

[crash-2024-02-13_02.39.55-client.txt](https://github.com/AE2-UEL/AE2FluidCraft-Rework/files/14260519/crash-2024-02-13_02.39.55-client.txt)

It only happens in this terminal as far as I have found but I suspect that it will crash in any terminal that can autocraft not in base AE2UEL

**Comment by GlodBlock** [comment]
please update to the latest ae2
