### ISSUE TITLE
java.lang.NoClassDefFoundError: appeng/client/gui/MathExpressionParser

### ISSUE THREAD

**Issue by baifeiajdj** [GlodBlock/AE2FluidCraft-Rework#143]
[Uploading crash-2024-02-19_19.47.48-client.txt…]()

**Comment by GlodBlock** [comment]
it seems that you failed to upload the log file
please update to the latest ae2 and try again

**Comment by NotMyWing** [comment]
Please update [AE2 Extended Life](https://www.curseforge.com/minecraft/mc-mods/ae2-extended-life).
