### ISSUE TITLE
Ordering automatic crafting in ME Fluid Pattern Terminal causes crash.

### ISSUE THREAD

**Issue by Herminos** [GlodBlock/AE2FluidCraft-Rework#144]
version:2.5.6-r
AE2UEL version: rv6-stable-7-extended_life-v0.55.27
ordering auto crafting in other terminal is normal.

**Comment by Herminos** [comment]
[crash-2024-02-26_09.18.03-client.txt](https://github.com/AE2-UEL/AE2FluidCraft-Rework/files/14398649/crash-2024-02-26_09.18.03-client.txt)
here's the crash report

**Comment by GlodBlock** [comment]
update to latest ae2
