### ISSUE TITLE
不完全支持Mek 气体

### ISSUE THREAD

**Issue by zeng-github01** [GlodBlock/AE2FluidCraft-Rework#153]
无二合一方块  合成从气体接口返回无效

**Comment by GlodBlock** [comment]
你有没有放一个叫气体离散器的东西
![image](https://github.com/AE2-UEL/AE2FluidCraft-Rework/assets/60341015/264e6cc9-fe78-4e19-9dd9-35de97e95e44)

**Comment by zeng-github01** [comment]
> 你有没有放一个叫气体离散器的东西 ![image](https://private-user-images.githubusercontent.com/60341015/329860568-264e6cc9-fe78-4e19-9dd9-35de97e95e44.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1Mjg0MTksIm5iZiI6MTcxNTUyODExOSwicGF0aCI6Ii82MDM0MTAxNS8zMjk4NjA1NjgtMjY0ZTZjYzktZmU3OC00ZTE5LTlkZDktMzVkZTk3ZTk1ZTQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEyVDE1MzUxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0ZDY5ODk3NmFmNTFmMWUyYWZhNGU4ZDVkZDEwNmU5MWRkNTUxYjNjYWZmODMxYjgzMGMxNWQ3Nzc4YmM3NDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PVLcxv0mRLWZ7aXFiGuXE0L-qRWbeGbr9RGKEs7w9ck)

系统里面是能看到气体的

**Comment by zeng-github01** [comment]
@GlodBlock 它只是单纯的不会对气体交互做出反应
比如下单气体合成，并不会通过接口输出气体，从AEA的气体接口输入系统，自动合成也没有反应

**Comment by zeng-github01** [comment]
可以单纯的认为，目前只能存储，但是既不能对外输出也不能输入

**Comment by zeng-github01** [comment]
@GlodBlock 话说作者，你这UI从哪搞得，这个UI框不是高版本才有的嘛

**Comment by zeng-github01** [comment]
> 你有没有放一个叫气体离散器的东西 ![image](https://private-user-images.githubusercontent.com/60341015/329860568-264e6cc9-fe78-4e19-9dd9-35de97e95e44.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1Mjg0MTksIm5iZiI6MTcxNTUyODExOSwicGF0aCI6Ii82MDM0MTAxNS8zMjk4NjA1NjgtMjY0ZTZjYzktZmU3OC00ZTE5LTlkZDktMzVkZTk3ZTk1ZTQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEyVDE1MzUxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0ZDY5ODk3NmFmNTFmMWUyYWZhNGU4ZDVkZDEwNmU5MWRkNTUxYjNjYWZmODMxYjgzMGMxNWQ3Nzc4YmM3NDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PVLcxv0mRLWZ7aXFiGuXE0L-qRWbeGbr9RGKEs7w9ck)

退一步说，不放离散器我怎么下单

**Comment by GlodBlock** [comment]
我这里是能的 https://imgur.com/a/W0zJ1dd
你有没有在存储元件上放黏性卡

**Comment by zeng-github01** [comment]
> 我这里是能的 https://imgur.com/a/W0zJ1dd
> 你有没有在存储元件上放黏性卡
> 

没有，我从来没用过这个卡，话说这个卡看起来很抽象，是什么用途

我的设计是把接口放机器底下，接口连线。气体倒是都收到了，但是压根没用，合成不显示完成。回头再试试看

**Comment by zeng-github01** [comment]
> > 我这里是能的 https://imgur.com/a/W0zJ1dd
> > 你有没有在存储元件上放黏性卡
> > 
> 
> 没有，我从来没用过这个卡，话说这个卡看起来很抽象，是什么用途
> 
> 我的设计是把接口放机器底下，接口连线。气体倒是都收到了，但是压根没用，合成不显示完成。回头再试试看

现在想想可能是Mek的问题，侧面可能没配置好，材料物品放不进。中间可能操作了一下，光把气体弄进去了
