### ISSUE TITLE
请添加气体二合一接口

### ISSUE THREAD

**Issue by zeng-github01** [GlodBlock/AE2FluidCraft-Rework#154]
目前我所使用的Mek分支正在测试单面输入输出功能。但是AE2FC暂时没有相关的组件

@GlodBlock  考虑到AEAddition 的气体接口的实现过于不规范。建议作者自行实现一个气体接口的API。不要尝试使用AEA 原有的。因为它的接口使用的是Kotlin 实现

我正在尝试重写这部分，但这不可避免的会损坏原有的气体接口。难以操作。除非有办法将现有的AEA 气体接口以弃用方块的形式进行处理。我对KT语言不熟

同时这部分补丁由于会变成我的私货，也无法同步给所有的玩家。因为我并不会使用CruseForge上传Mod

**Comment by GlodBlock** [comment]
加了
