### ISSUE TITLE
有关AE2的新PR

### ISSUE THREAD

**Issue by zeng-github01** [GlodBlock/AE2FluidCraft-Rework#157]
UEL那边最近新上了一个PR ，准备原生支持流体合成了。到时候AE2FC就可以退休了啊....作者你怎么看？ @GlodBlock 
这好活也整的太狠了。真怕它扯到蛋

**Comment by GlodBlock** [comment]
那个pr能在一年内合并都算快的

**Comment by zeng-github01** [comment]
主要是这个PR整上去之后，隔壁的气体支持就危险了。我自己有一个给UEL用的Fork。但是我不会玩CurseForge

**Comment by ghost** [comment]
感觉没有必要啊，现在ae2fcr就挺好的，而且我看也在AE2UEL的官方组织仓库里

**Comment by zeng-github01** [comment]
> 感觉没有必要啊，现在ae2fcr就挺好的，而且我看也在AE2UEL的官方组织仓库里

我暂时也不太懂。但是目前这个PR就是这样。说起自动合成就恼火，隔壁的ExtraCell弃坑了。另一个接坑的那个代码水平真是烂透了。还不知道抽什么风。要改EC的Modid。导致兼容性差的要死

AE2FCr的作者弄了个新的气体集成。这玩意比EC接坑的那个好多了。但是也会导致现有存在EC的气体出问题。光是迁移代码都折腾了半天

**Comment by zeng-github01** [comment]
@GlodBlock 要不作者你再努力一下，把我放在隔壁NAE的那个EC迁移issue的东西实现一下？至少实现一下气体磁盘，我好把EC目前的盘都换成NAE的 全都迁移过去。迁移完了之后就把我自用的分叉里面的所有盘都关了。或者我再改进一下，解决崩溃。

EC/AEA的代码耦合度太高了。改成MekE的存储通道虽然能用，但是会让AEA强制依赖MekE。后续我才反应过来，这玩意居然在枚举初始化的时候就创建新对象。所以哪怕这个枚举是要求MekE在线才注册方块。依然会因为class签名含有AE气体堆栈类而崩掉。怪不得

只能把这部分对象创建独立成一个方法了。
