### ISSUE TITLE
AE2 FCR doesn't work with nomifactory GTCEu.

### ISSUE THREAD

**Issue by goldencreepers** [GlodBlock/AE2FluidCraft-Rework#158]
for whatever reason, i'm unable to use fluid crafting in nomifactory GTCEu, as the ME system doesn't register the fluids.
what's the latest compatable version? and can anyone explain why i can't register the fluids when i try to use autocrafting?
![temp](https://github.com/AE2-UEL/AE2FluidCraft-Rework/assets/170782854/f874f90f-c0d3-4c1a-a28d-b731e404d346)
![temp](https://github.com/AE2-UEL/AE2FluidCraft-Rework/assets/170782854/76a8c11e-113a-4a1d-b712-57bd9c85f4bb)

**Comment by GlodBlock** [comment]
do you have fluid discretizer in your ae network?

**Comment by goldencreepers** [comment]
so THAT'S what it's for.

what does it do again?

**Comment by GlodBlock** [comment]
it makes ae can use fluid in crafting jobs

**Comment by goldencreepers** [comment]
okay, how many do i need, and more importanly, how do i use them?

**Comment by GlodBlock** [comment]
one. place it anywhere in your ae network. 
if you still don't understand, follow this wiki https://github.com/AE2-UEL/AE2FluidCraft-Rework/wiki/ME-Fluid-Discretizer

**Comment by goldencreepers** [comment]
thanks.
