### ISSUE TITLE
终极样板编码台Bug

### ISSUE THREAD

**Issue by zeng-github01** [GlodBlock/AE2FluidCraft-Rework#159]
当GUI中未提供原材料时，按下编码会导致样板凭空消耗

上次的issue 压根没修。只是更新了一个版本号，是不是操作失误

**Comment by KasumiNova** [comment]
草，我记得我报告过这个来着，还是没修吗

**Comment by zeng-github01** [comment]
> 草，我记得我报告过这个来着，还是没修吗

你可以看一下提交记录。应该是操作失误了，修复提交只更新了版本号

看起来作者没发现这个错误

**Comment by GlodBlock** [comment]
呃呃

**Comment by GlodBlock** [comment]
这次修了
