### ISSUE TITLE
What do you think this(an ae2fc fork by using forked PackagedAuto that have 18 output)

### ISSUE THREAD

**Issue by ghost** [GlodBlock/AE2FluidCraft-Rework#16]
I suddenly see this pull request https://github.com/phantamanta44/ae2-fluid-crafting/pull/18
its repository
https://github.com/123FLO321/ae2-fluid-crafting/tree/1.12-18-outputs
it use the forked PackagedAuto
https://github.com/123FLO321/PackagedAuto/tree/1.12-18-outputs

**Comment by GlodBlock** [comment]
that pr seems completely ignored by miffy lol.
but anyway, you can use pack auto to make recursive patterns that can have 9+ outputs. it more like something should be done in pack auto side instead of here
