### ISSUE TITLE
[Bug] 服务端随机Crash

### ISSUE THREAD

**Issue by zeng-github01** [GlodBlock/AE2FluidCraft-Rework#161]
[crash-2024-06-15_16.41.50-server.txt](https://github.com/user-attachments/files/15846262/crash-2024-06-15_16.41.50-server.txt)

**Comment by GlodBlock** [comment]
看不出哪里出问题，你用的ae版本和附属有哪些

**Comment by zeng-github01** [comment]
> 看不出哪里出问题，你用的ae版本和附属有哪些

本体0.56.5，Mek支持组件，微调过的AEAdditions， NAE2

**Comment by GlodBlock** [comment]
主要你这个崩溃很没有道理，那个地方绝对不可能会是null的，以前也从来没有人报告过这种崩溃

**Comment by zeng-github01** [comment]
> 主要你这个崩溃很没有道理，那个地方绝对不可能会是null的，以前也从来没有人报告过这种崩溃

这个问题疑似是AE本体的毛病。我去本体那提一个issue
