### ISSUE TITLE
Interface Blocking mode does not respect fluids in GTCEu Quad Hatches

### ISSUE THREAD

**Issue by pyure** [GlodBlock/AE2FluidCraft-Rework#162]
**1.12.2
AE2-2.6.1-r.jar
GTCEu 2.8.7-beta**

**To reproduce:**
- Build a GTCEu Large Chemical Reactor with a Quad input hatch
- Connect it to an AE2 network (with discretizer etc)
- Ensure it has access to Oxygen and Nitrogen
- Create a recipe pattern for it to create Oxygen + Nitrogen -> Nitrogen Dioxide (requires an input buffer with circuit 3 configured)
- Attach an interface to the Quad Input Hatch 
   - **Important**: do not face the hatch at the interface or it may _pull_ fluids, invalidating the test
   - Does not matter if you use a regular interface vs a dual; both will exhibit the same behaviour
- Use Blocking Mode - Block All (Items and Fluids)
- Put the nitrogen dioxide pattern into the interface
- Put a random fluid into a slot of the quad interface (neither oxygen nor nitrogen)
- Request nitrogen dioxide

**Expected outcome:**
- The recipe should fail to execute because the hatch has a blocking fluid present
- Reasoning: Item-based blocking will block execution of a recipe in e.g. an Assembling Machine even if only 1 slot is blocked and there's plenty of "room" for the ingredients.  Same should be true for fluid-based blocking.  

**Actual outcome**
- The recipe will execute, possibly triggering an undesirable recipe with your random fluid if one such matches

Somewhat related to #116

**Comment by GlodBlock** [comment]
fixed by https://github.com/AE2-UEL/AE2FluidCraft-Rework/commit/fd5fa383f809bed0bf2840d53e5f3a4c3d7a571b
