### ISSUE TITLE
Fluid assembler get items but doesnt craft

### ISSUE THREAD

**Issue by gustavodm2** [GlodBlock/AE2FluidCraft-Rework#167]
I already did the fluid discretizer
![image](https://github.com/user-attachments/assets/45a52228-35db-4af2-832a-53a45d61928d)
It stays like this, but doesnt actually craft the item

**Comment by GlodBlock** [comment]
it only accepts the blue pattern from fluid pattern encoder
![image](https://github.com/user-attachments/assets/d7f06c45-6c2b-4f2e-8234-63614ae9b3f2)
click this button to encode, it must be craft recipe that contains fluid bucket input
![image](https://github.com/user-attachments/assets/b3c4b996-62fc-4cab-aeb2-14360ed786ee)
