### ISSUE TITLE
Cannot use NAE2 Programmed Circuit Card in the Dual Interface

### ISSUE THREAD

**Issue by GavinFF-SS** [GlodBlock/AE2FluidCraft-Rework#168]
Shift-clicking it in causes it to go back to storage, and I can't put it in manually. Help on this would be appreciated.

**Comment by CactusCool** [comment]
this is something you will have to ask neeve to support in nae2, not here. it doesnt go in the dual interface becaues the dual interface doesnt support it. Also I hope your aware that a regular interface can output fluids so you dont actually have to use a dual interface.

**Comment by GavinFF-SS** [comment]
oh, alright, my fault
