### ISSUE TITLE
[1.12] Fluids entering the network ignore storage bus partitions

### ISSUE THREAD

**Issue by ren-** [GlodBlock/AE2FluidCraft-Rework#174]
# Description

Fluid storage bus ignores the partition filter when the fluid entering the system doesn't have a place to go and inserts into a random destination (regardless of partitions).
> [!NOTE]  
> Removing the FCR mod solves the issue. Tested with the latest 4 versions of this mod - the issue persists.

[fluidstoragebus.webm](https://github.com/user-attachments/assets/57ab6fc7-8b96-4cd9-b32c-6dd2ecc8713a)

# Mods
latest nomi-ceu 1.7a
ae2-uel 0.56.5
nae2-1.6.4

## Network structure
Fluid storage bus (oxygen), Fluid storage bus (water), ME fluid interface

## Actual behavior
Put nitrogen into the interface -> nitrogen goes to the tank with oxygen partition

## Expected behavior 
Put nitrogen into the interface -> it gets stuck as there is no destination available

**Comment by GlodBlock** [comment]
it is ae2's issue
