### ISSUE TITLE
Possible enchancments/bugs for fluid interface and patterns

### ISSUE THREAD

**Issue by Ydrec** [GlodBlock/AE2FluidCraft-Rework#18]
If pattern in fluid interface contains both item and fluid then it needs an inventory which can accept both at same time to actually output anything when craft task created. (It would however work fine if pattern contains only item or only fluid input) 
(It also would properly divide items/fluids for items going after the first item/fluid bundle, like if i have a tank above which can accept only 1 item and 1 fluid other items in pattern would properly divide between tanks/chests around fluid interface)

In 1.7.10 version normal interface delivers a fluid package item instead of fluid. Don't know if thats a bug.

In fluid interface its impossible to encode an item containing fluid as an actual item, possibly add a feature to hold shift so fluid pattern interface doesn't turn container to liquid package.

**Comment by GlodBlock** [comment]
> If pattern in fluid interface contains both item and fluid then it needs an inventory which can accept both at same time to actually output anything when craft task created. (It would however work fine if pattern contains only item or only fluid input) (It also would properly divide items/fluids for items going after the first item/fluid bundle, like if i have a tank above which can accept only 1 item and 1 fluid other items in pattern would properly divide between tanks/chests around fluid interface)
> 
you can use ingredient buffer to hold the input from the interface as a solution now. will fix it later.
> In 1.7.10 version normal interface delivers a fluid package item instead of fluid. Don't know if thats a bug.
> 
that is intended normal me interface output fluid package. you can disable this feature in config file, then it will output fluid like fluid interface.
> In fluid interface its impossible to encode an item containing fluid as an actual item, possibly add a feature to hold shift so fluid pattern interface doesn't turn container to liquid package.

ok

**Comment by GlodBlock** [comment]
> If pattern in fluid interface contains both item and fluid then it needs an inventory which can accept both at same time to actually output anything when craft task created. (It would however work fine if pattern contains only item or only fluid input) (It also would properly divide items/fluids for items going after the first item/fluid bundle, like if i have a tank above which can accept only 1 item and 1 fluid other items in pattern would properly divide between tanks/chests around fluid interface)

further investigation, that is actually a bug in ae2. i can't fix it at my side.

>In fluid interface its impossible to encode an item containing fluid as an actual item, possibly add a feature to hold shift so fluid pattern interface doesn't turn container to liquid package.

now you can hold `alt` to code with fluid container
