### ISSUE TITLE
Git GTNH

### ISSUE THREAD

**Issue by Pilad** [GlodBlock/AE2FluidCraft-Rework#19]
Maybe you will find some fixes or something new here.
https://github.com/GTNewHorizons/AE2FluidCraft-Rework/commits/master

**Comment by GlodBlock** [comment]
that's version and workflow thing. it doesn't need. :)

**Comment by Pilad** [comment]
> that's version and workflow thing. it doesn't need. :)

Maybe in the future, for example, interesting functionality in the mod or fixes will appear in the gtnh build, maybe you should follow this version of the fork?

**Comment by GlodBlock** [comment]
i will pull anything useful from other forks. but gtnh fork is going to only serve for gtnh edition ae2
