### ISSUE TITLE
Doesn't work with standard version of NEI

### ISSUE THREAD

**Issue by Pilad** [GlodBlock/AE2FluidCraft-Rework#2]
MC v1.7.10
Doesn't work with standard version of NEI, crash from class https://github.com/GlodBlock/AE2FluidCraft-Rework/blob/1.7.10/src/main/java/com/glodblock/github/nei/recipes/extractor/ForestryRecipeExtractor .java and codechicken\nei\recipe\IRecipeHandler.java

**Comment by GlodBlock** [comment]
fixed now
https://www.curseforge.com/minecraft/mc-mods/ae2-fluid-crafting-rework/files/3796722
