### ISSUE TITLE
Dual Fluid Interface

### ISSUE THREAD

**Issue by darkbumerang** [GlodBlock/AE2FluidCraft-Rework#20]
Hi. In version 1.7.10 in creative mode, you can not see the tab of this mod in the inventory. And also the double liquid interface is not available in the inventory and in NEI it is not visible. 
ps. Checked the version 1.12.2 - everything is available there.
ps2. Very much want to give up ExtraCells...

**Comment by GlodBlock** [comment]
>ps2. Very much want to give up ExtraCells...

there are lots of patched version of ec2 in both 1.7.10 and 1.12.2. like ae2 addition or some modpack edition ec2(gtnh, impact).
>And also the double liquid interface is not available in the inventory and in NEI it is not visible.

the `double liquid interface` in 1.7.10 is called fluid interface, check that. 
>In version 1.7.10 in creative mode, you can not see the tab of this mod in the inventory.

the tab thing can be fixed soon.

**Comment by darkbumerang** [comment]
> the double liquid interface in 1.7.10 is called fluid interface, check that.

Checked now on 1.7.10. There is no toggle button in the liquid interface to use it as an analogue of the liquid interface from Extra Cells 2
![изображение](https://user-images.githubusercontent.com/17011348/175028971-6d95c9ad-4c3a-4db0-b35c-8900dd0fd500.png)

**Comment by darkbumerang** [comment]
Hi. I got a new version built with the latest changes in the code. Now the liquid interface shows the toggle button correctly and it works. Also liquids are loaded into it from the network, but pipes from EnderIO do not unload liquids from the interface from either side.
ps. Will the fluidic level emmiter appear in this mod? This is the only critical item that would give up EC2 forever :)

**Comment by GlodBlock** [comment]
> Hi. I got a new version built with the latest changes in the code. Now the liquid interface shows the toggle button correctly and it works. Also liquids are loaded into it from the network, but pipes from EnderIO do not unload liquids from the interface from either side. 

because it hasn't finished yet. i only did the gui thing. i will publish it in tag or curseforge the first time when it is fully done.
>ps. Will the fluidic level emmiter appear in this mod? This is the only critical item that would give up EC2 forever :)

i will backport the fluid level maintainer first, which is similar to fluid level emmiter.
