### ISSUE TITLE
It is not possible to extract liquids with pipes from the interface.

### ISSUE THREAD

**Issue by Pilad** [GlodBlock/AE2FluidCraft-Rework#21]
I assembled the mod, but you can't take the indicated liquids from the interface with pipes. For example with mod ender.io. Also in the GUI of the interface there is no indication of the side of the world, and Waila does not show the side of the world if you look at the interface. The extra сells mod has this display both in the GUI and in Waila.
https://github.com/GlodBlock/AE2FluidCraft-Rework/commit/475842d115a7c6120e0daafa2b6f7a0c56113f29

**Comment by GlodBlock** [comment]
because it hasn't finished yet. i only did the gui thing. i will publish it in tag or curseforge the first time when it is fully done.

**Comment by Pilad** [comment]
> because it hasn't finished yet. i only did the gui thing. i will publish it in tag or curseforge the first time when it is fully done.
Bugs: The interface gives out only the first liquid on all sides. There is no display of sides in the Waila and in the GUI interface.
https://github.com/GlodBlock/AE2FluidCraft-Rework/commit/19f9dee682291f546be186ce8057aa3e2149026f
