### ISSUE TITLE
Interaction of the dual fluid interface with the EnderIO conduit

### ISSUE THREAD

**Issue by darkbumerang** [GlodBlock/AE2FluidCraft-Rework#22]
Hi. Checked the operation of the dual liquid interface. When unloading three kinds of fluids at once from the interface into one pipe (Ender conduit) and then into 3 different quartz tanks, having installed filters on them for each of the fluids - only the fluid that is first on the list in the pipe is poured into the tank. Tested with fluid interfaces from ExtraCells 2 - there fluids are poured into three tanks at once - each fluid in its own tank.

**Comment by GlodBlock** [comment]
skill issue. ec2's interface is using different faces to output fluids in corresponding slot.

**Comment by darkbumerang** [comment]
Hello. 
What do you mean by skill issue?
You mean you can't make fluids transfer normally through the Ender conduit? Sad =(
![iis1](https://user-images.githubusercontent.com/17011348/175921902-a3ef14ff-96dc-41d6-8bea-3a0683b7a9b7.png)
![iis2](https://user-images.githubusercontent.com/17011348/175921913-74d88d87-4574-4f91-9617-c9f27baa60f8.png)

**Comment by GlodBlock** [comment]
idk, the same code works in 1.12 but failed in 1.7.10. using the ec2 way to output fluid will work but i don't like output fluid by side

**Comment by darkbumerang** [comment]
> idk, the same code works in 1.12 but failed in 1.7.10. using the ec2 way to output fluid will work but i don't like output fluid by side

Hmm. Maybe temporarily use the EC2 way until inspiration comes to solve the output problem on one side? At that time, the interface will be fully functional. =)

**Comment by Pilad** [comment]
> idk, the same code works in 1.12 but failed in 1.7.10. using the ec2 way to output fluid will work but i don't like output fluid by side

Can see how extra cell is done in fashion and this will help to understand the reason for the inoperability

**Comment by GlodBlock** [comment]
that is actually a bug a ender io and i have made the pr for gtnh fork ender io to fix it, so it should works in nh update.
but anyway most logics mods in 1.7.10 have such bug, i will add something like fluid router as a workaround to handle it.

**Comment by Pilad** [comment]
> that is actually a bug a ender io and i have made the pr for gtnh fork ender io to fix it, so it should works in nh update. but anyway most logics mods in 1.7.10 have such bug, i will add something like fluid router as a workaround to handle it.

I used a pipe from the gregtech mod, the first liquid is also pushed out on all sides. It does not depend on the type of pipe or the mod where the pipe comes from

**Comment by GlodBlock** [comment]
gt5 also has this bug, not sure whether gt6 has it.
> i will add something like fluid router as a workaround to handle it.

this is the solution i chose

**Comment by Pilad** [comment]
> gt5 also has this bug, not sure whether gt6 has it.
> 
> > i will add something like fluid router as a workaround to handle it.
> 
> this is the solution i chose

One if the mod is with a bug, I agree. You need to fix the mod. But if all mods with pipes are also bugged, you have a bug in your mod.
Moreover, the extra cell interface works great with all pipes from any mod. Although it is not well written.

**Comment by GlodBlock** [comment]
ok

**Comment by Pilad** [comment]
> ok

That's why I suggested looking at the implementation of the interface with extra cells. Can take the principle of distributing liquids to the sides of the block from this mod.
Maybe this will help solve the problem that in the current code does not work. In order not to add code to the same ender io or gregtech or thermal dynamics, etc.

**Comment by GlodBlock** [comment]
try this https://github.com/GlodBlock/AE2FluidCraft-Rework/releases/tag/g3e5563c

**Comment by Pilad** [comment]
> try this https://github.com/GlodBlock/AE2FluidCraft-Rework/releases/tag/g3e5563c

New bug ) https://github.com/GlodBlock/AE2FluidCraft-Rework/issues/23
