### ISSUE TITLE
Item does not enter the ME network

### ISSUE THREAD

**Issue by Pilad** [GlodBlock/AE2FluidCraft-Rework#23]
After completing the recipe in the machine, the item does not enter the ME network, it remains in the interface.
https://ltdfoto.ru/images/2022/06/30/meInt.png

**Comment by Pilad** [comment]
And if you place items in the upper slots, then they also do not go to the ME network.

**Comment by GlodBlock** [comment]
is the block form interface also broken, or only the part form one broken?

**Comment by Pilad** [comment]
> is the block form interface also broken, or only the part form one broken?

only part form broken

**Comment by GlodBlock** [comment]
should be fixed now https://github.com/GlodBlock/AE2FluidCraft-Rework/releases/tag/ge8b2801
