### ISSUE TITLE
Dual interface energy consumption

### ISSUE THREAD

**Issue by darkbumerang** [GlodBlock/AE2FluidCraft-Rework#25]
Hi. Found a problem with the power consumption of the dual liquid interface and other.

1. Created a template to create tungsten (x4 Tugnsten Trioxide Dust + 6,000mb hydrogen) put it in the liquid interface EC2, ordered the creation of 64 ingots of tungsten - the power consumption is 21.48eu\t exactly what the network AE2 consumes before running the recipe. The liquid interface itself is only connected to the AE2 network.
The same recipe but using hydrogen not in capsules, as in the first time but already in liquid form, then put the template in the dual liquid interface and run the recipe - the power consumption has increased to 6kEU/t.
If you empty the buffer of the dual interface completely, the power consumption drops to normal values.

2. The liquid interface from EC2 unloads items to the Input bus connected to it, but the dual interface does not. If you put a chest on the two-way interface and point the interface with an arrow towards the chest and order the recipe described above, it unloads into the chest Tugnsten Trioxide Dust and hydrogen drops...

**Comment by GlodBlock** [comment]
> 2\. The liquid interface from EC2 unloads items to the Input bus connected to it, but the dual interface does not

if the pattern contains both liquid and items, you will need to use a ingredient buffer to store the material and then distribute them. if the pattern is items only, i believe it works.




> 2\. If you put a chest on the two-way interface and point the interface with an arrow towards the chest and order the recipe described above, it unloads into the chest Tugnsten Trioxide Dust and hydrogen drops...

can't reproduce that. if use a normal interface and with `No Fluid Packet` disabled, it should output fluid packet. if use dual interface, it won't output anything. could you provide a screenshot of the bug setup?

> 1. If you empty the buffer of the dual interface completely, the power consumption drops to normal values.

that seems like an ae2 side problem, ae2 handles every 1mb fluid as 1 item so it may cause ridiculous power usage when i/o fluids. ec2 directly ignores the fluid i/o power usage so it won't drain a lot power when running, should we also follow that?

**Comment by darkbumerang** [comment]
> if the pattern contains both liquid and items, you will need to use a ingredient buffer to store the material and then distribute them. if the pattern is items only, i believe it works.

Thank you. I think I can use an interface with a buffer, although 1 block more than in EC2 =)

> can't reproduce that. if use a normal interface and with No Fluid Packet disabled, it should output fluid packet. if use dual interface, it won't output anything. could you provide a screenshot of the bug setup?

Sorry, I inserted a coded pattern under AE2Fc (purple) into the EC2 liquid interface, then the EC2 interface started unloading drops %-)

> that seems like an ae2 side problem, ae2 handles every 1mb fluid as 1 item so it may cause ridiculous power usage when i/o fluids. ec2 directly ignores the fluid i/o power usage so it won't drain a lot power when running, should we also follow that?

Hmm. I was given a hint that you are using not standard version of AE2 (from GTNH) when building. We use the standard version of AE2 from curseforge...
I checked with the version of AE2 from curseforge [https://www.curseforge.com/minecraft/mc-mods/applied-energistics-2/files/2296430](url) and this power consumption bug appears there.

**Comment by GlodBlock** [comment]
> Hmm. I was given a hint that you are using not standard version of AE2 (from GTNH) when building. We use the standard version of AE2 from curseforge...
> I checked with the version of AE2 from curseforge [https://www.curseforge.com/minecraft/mc-mods/applied-energistics-2/files/2296430](url) and this power consumption bug appears there.

the gtnh fork ae2 also has such problem(the energy consumption will rise ripidly when clear/fill the buff), so i decide to revert the energy use in fluid i/o before finding a more reasonable slolution

**Comment by GlodBlock** [comment]
try this https://github.com/GlodBlock/AE2FluidCraft-Rework/releases/tag/g07b03d1

**Comment by darkbumerang** [comment]
> try this https://github.com/GlodBlock/AE2FluidCraft-Rework/releases/tag/g07b03d1

Works great. Energy consumption, when crafting the same amount of ingots as last time, now increases energy consumption from 10.9eu\t to 15eu\t.
