### ISSUE TITLE
[1.7.10] Thaumcraft essentia can be stored in ME fluid storage cells

### ISSUE THREAD

**Issue by Vapaman** [GlodBlock/AE2FluidCraft-Rework#27]
**Mods**
Thaumic Energistics (1.3.19-GTNH)
Thaumcraft
Applied Energistics (rv3-beta-83-GTNH)
AE2 Fluidcraft Rework (ge8b2801)

Essentia is internally processed as a fluid, so essentia can be put in fluid storage cells. An easy fix would be to blacklist essentia from being put into fluid cells.

**Comment by GlodBlock** [comment]
fixed by https://github.com/GlodBlock/AE2FluidCraft-Rework/commit/61cdd8c487ca8b9e5b6c1d4e01107bfeb3fdd85c
