### ISSUE TITLE
Render crash.

### ISSUE THREAD

**Issue by Pilad** [GlodBlock/AE2FluidCraft-Rework#3]
Not works? The button is not active for crafting. Although sold. alloy is present in liquid form. 
Video: https://cloud.mail.ru/public/ccZf/FH38DY3yK

Crash
left click on items 0:14
Video: https://cloud.mail.ru/public/YCQf/PFPXSRsje
https://pastebin.com/LhXppCyR

**Comment by Pilad** [comment]
Mod last version ae2fc-1.7.10-c45419a

**Comment by Pilad** [comment]
Also crash on button CANCEL(left click)
https://pastebin.com/WxdL1tb0
 time: 0.12
https://cloud.mail.ru/public/YCQf/PFPXSRsje

**Comment by GlodBlock** [comment]
the crash is some oversight in code. as to the missing fluid, i think you should use molten pe for smd capacitor instead of solding alloy.
try this one, it should fix the render crash
[ae2fc-1.7.10-99c6ccd.zip](https://github.com/GlodBlock/AE2FluidCraft-Rework/files/8729437/ae2fc-1.7.10-99c6ccd.zip)

**Comment by Pilad** [comment]
> 
Exactly, thanks. I was careless when coding the recipe. And the fact that the disks from the mod can hold only one liquid is the way it should be. In the extra cels mod, the discs can hold 5 types of fluids.
Capacitors are now created without errors. And there is no render error.

**Comment by GlodBlock** [comment]
> > 
> 
> Exactly, thanks. I was careless when coding the recipe. And the fact that the disks from the mod can hold only one liquid is the way it should be. In the extra cels mod, the discs can hold 5 types of fluids. Capacitors are now created without errors. And there is no render error.

that is intended
