### ISSUE TITLE
版本号g411ec67无法往流体存储元件里存液体

### ISSUE THREAD

**Issue by SuPer-CY1020** [GlodBlock/AE2FluidCraft-Rework#36]
至少我在版本g3ebf64f中从NEI里掏出来的FC版4096K流体元件在版本g411ec67中无论如何都无法正常工作，不管是从接口导入还是流体终端直接存都不行，回滚到g3ebf64f后一切正常

**Comment by GlodBlock** [comment]
已修复，但是我还没发布release

**Comment by GlodBlock** [comment]
用这个https://github.com/GlodBlock/AE2FluidCraft-Rework/releases/tag/gd7d22c1
