### ISSUE TITLE
Rudeless consume of EU energy (GTCEu) 

### ISSUE THREAD

**Issue by nemo48rus** [GlodBlock/AE2FluidCraft-Rework#39]
I play on TerraFirmaGreg R3.0-R4.0 and I so much enjoyed your mod! Its easiest way to code fluids. Thanks!

But at early (hv-ev-iv era's) have troubles with energy consumption.
With 8xHV input we have restart ME every 1-5 secs with full energy hatch and 1 small AE buffer (100kAE).

We set more connections to MEwith cables, gain them more ampers, but I think it isnt solution.

Thanks for reading!

**Comment by GlodBlock** [comment]
does this energy consumption problem always happen or only happen in certain conditions (like hveay fluid i/o in network or request fluid crafting jobs)

**Comment by nemo48rus** [comment]
Only when start big craft like 15000 oxygen; 15000 hydrogen in one time - craft dont export, but consumping all energy and lock down ME controller.
Like 1k oxy, 1k hydrogen - work +- good.

**Comment by nemo48rus** [comment]
Or it can be many 1k crafts, but very frueqently - dont work correctly

**Comment by GlodBlock** [comment]
ok it seems similar to https://github.com/GlodBlock/AE2FluidCraft-Rework/issues/25 in 1.7.10. should be an easy fix

**Comment by GlodBlock** [comment]
fixed by https://github.com/GlodBlock/AE2FluidCraft-Rework/commit/77c3201e23d9479853accfe08f9d66ec1f5f32e8.
you can use 2.3.4-r jar in tags. cf update is soon

**Comment by nemo48rus** [comment]
> fixed by https://github.com/GlodBlock/AE2FluidCraft-Rework/commit/77c3201e23d9479853accfe08f9d66ec1f5f32e8.
> you can use 2.3.4-r jar in tags. cf update is soon

Thank you
