### ISSUE TITLE
Allows the use of the middle mouse button to modify the number of items in the pattern.

### ISSUE THREAD

**Issue by Pilad** [GlodBlock/AE2FluidCraft-Rework#40]
You do not plan to make compatibility like on GTNH?
https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/pull/160
Here is the PR for the mod
https://github.com/GTNewHorizons/AE2FluidCraft-Rework/pull/9

**Comment by GlodBlock** [comment]
will do it later

**Comment by GlodBlock** [comment]
added by https://github.com/GlodBlock/AE2FluidCraft-Rework/commit/572e6259d9167ba91fb1a8ebd600eea038bd9c2c
