### ISSUE TITLE
Opening priority gui in dual interface causes crash

### ISSUE THREAD

**Issue by Ydrec** [GlodBlock/AE2FluidCraft-Rework#41]
2.1.2.4_dev29

without any additional mods

[crash-2022-08-26_21.21.33-client.txt](https://github.com/GlodBlock/AE2FluidCraft-Rework/files/9435647/crash-2022-08-26_21.21.33-client.txt)

**Comment by GlodBlock** [comment]
it is a gtnh edition issue, so you should post it in nh side.
also it has fixed by https://github.com/GTNewHorizons/AE2FluidCraft-Rework/commit/a0e6277a3bd183adcca39bd876bd767d38b58205. use this build on jenkins http://jenkins.usrv.eu:8080/job/AE2FluidCraft-Rework/24/
