### ISSUE TITLE
Cannot craft cables in Assembling machine (GregTech 5.09)

### ISSUE THREAD

**Issue by tyxa** [GlodBlock/AE2FluidCraft-Rework#46]
Putting encoded pattern in dual interface without integrated circuit (24) doesnt let you craft cables.
![image](https://user-images.githubusercontent.com/17194752/190857748-523c77f2-144d-4500-b9c6-9341e691b96d.png)
and with blocking mode that ignore content of the target inventory it just doesnt work.
removing integrated circuit, items apear in interface
![image](https://user-images.githubusercontent.com/17194752/190857837-eb54220d-907c-4bb9-ab5a-caedd2e78571.png)
![image](https://user-images.githubusercontent.com/17194752/190857843-19598004-4903-4836-b886-56ad6b3111cc.png)
![image](https://user-images.githubusercontent.com/17194752/190857854-d2dc1f11-025d-4b3c-a76a-02d56dc8606a.png)
![image](https://user-images.githubusercontent.com/17194752/190857865-bd5d5c82-35ed-48d6-87cb-3b558bc47509.png)

**Comment by GlodBlock** [comment]
blocking mode is to not output when there is contents in target container. so you should turn off the blocking mode if you put the circuit in assembler

**Comment by tyxa** [comment]
> 

it is turned off (see screenshot)

**Comment by GlodBlock** [comment]
hmmmm. then try to disable the input filter of the gt machine, shift + right mouse click to machine with screwdriver
![image](https://user-images.githubusercontent.com/60341015/190859855-d229d3dd-b8f6-43a3-988c-d5a6364278ed.png)

**Comment by tyxa** [comment]
![image](https://user-images.githubusercontent.com/17194752/190860418-ff1f3cca-1d15-497e-a956-4607cf31d8bc.png)
each side with screwdriver just change input behaviour.
when i remove circuit from machine, dual interface put items to machine, but if circuit already in machine it doesn't

**Comment by GlodBlock** [comment]
do you hold `shift`?

**Comment by tyxa** [comment]
> 

yes.
GT 5.09.28

**Comment by tyxa** [comment]
![image](https://user-images.githubusercontent.com/17194752/190861080-3f74d4c5-714d-4c03-bdcd-7f951239a254.png)
that pattern with 144 drop of molten rubber have same behavior, doesnt appear when circuit in machine

**Comment by tyxa** [comment]
when machine have an item in any input slot, dual interface doesnt put items in, but fluids does
try with that mode:
![image](https://user-images.githubusercontent.com/17194752/190861405-72e130c4-8130-4ebb-9caa-64133454d587.png)

**Comment by GlodBlock** [comment]
figure it out. it is a gt5u side bug https://github.com/Blood-Asp/GT5-Unofficial/commit/a625088776675f9baec9149728f2b622281391e6, updating to 5.09.31 should fix that.
[gregtech-5.09.31.zip](https://github.com/GlodBlock/AE2FluidCraft-Rework/files/9591880/gregtech-5.09.31.zip)
unzip this
