### ISSUE TITLE
Incorrect bytes requirement calculation when input fluid isn't sufficient

### ISSUE THREAD

**Issue by xyqyear** [GlodBlock/AE2FluidCraft-Rework#49]
When crafting fluid, if the input fluid isn't sufficient, the crafting simulation shows incorrect bytes requirement
![image](https://user-images.githubusercontent.com/29950788/193817501-6e438035-79ae-472a-80bc-417b33699d23.png)
If the input fluid is sufficient, the calculation is correct
![image](https://user-images.githubusercontent.com/29950788/193817646-de1d100c-d61e-4cda-a746-567cf3deaa20.png)

### Problem analysis

ae2fc modifies ae2's code so that when the crafting process is crafting fluid drops, the item stack size used for bytes requirement calculation is divided by 1000. This process is done through the following code snippets

https://github.com/GlodBlock/AE2FluidCraft-Rework/blob/e5d40ae7ec347be95e08ec57322b7ccab1e75efb/src/main/java/com/glodblock/github/coremod/transform/CraftingTreeNodeTransformer.java#L61-L69

https://github.com/GlodBlock/AE2FluidCraft-Rework/blob/e5d40ae7ec347be95e08ec57322b7ccab1e75efb/src/main/java/com/glodblock/github/coremod/hooker/CoreModHooks.java#L71-L74

The above code modifies [`CraftingTreeNode`](https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/blob/master/src/main/java/appeng/crafting/CraftingTreeNode.java) when a `IAEItemStack`'s getStackSize is called in line 152, 174, 188 and 208

However, it only considers the part that already exists in the network or can be crafted. The part that's missing is directly added to bytes property of CraftingTreeNode without the division.

![image](https://user-images.githubusercontent.com/29950788/193823631-912347f7-0a25-4f49-9f89-0fa27d118f4c.png)
[note 1]

This is a code snippet of [`CraftingTreeNode` line 233-255](https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/blob/d38c2a6e5488a2c60c465d76f82de3a2a3042934/src/main/java/appeng/crafting/CraftingTreeNode.java#L233-L255) [note 2]. The first line of code block 1 is modified by ae2fc, however, the local variable `l` (number of items that still needed to be crafted. You can see in the following if statement, if it's less than 0, then return excessive item stack) isn't modified by a factor of 1/1000. In code block 2 (this if statement is only effective when the item is insufficient, meaning not enough in the network nor can be crafted), the variable `l` is directly added to `this.bytes`, resulting in the bug of the subject matter.

### Possible solution

modify line 251 of CraftingTreeNode to `this.bytes += l / 1000L;`. Of course, we can't just modify the exact line, just somehow locate the line where `this.bytes` is added by `l`. Variable `l` shouldn't be modified because it tells the user how much more fluid is still needed.

Due to my unfamiliarity with the ASM library, I can only present a possible solution rather than submitting a PR.

note 1: code from external repo can't be rendered as a code block, so I used a screenshot
note 2: this is only one of the four places where `this.bytes` is added by an `IAEItemStack`'s `getStackSize()`

**Comment by GlodBlock** [comment]
honestly i really don't want fix it since you can't order crafting job without enough input so the bytes doesn't matter :doom:
but a fix is still doable though it needs more hacky asm injection

**Comment by GlodBlock** [comment]
fixed by https://github.com/GlodBlock/AE2FluidCraft-Rework/commit/0221c24f2819f9b73af49fb6d079cf40b95e0677
