### ISSUE TITLE
Add fluid terminal/fluid import/export bus.

### ISSUE THREAD

**Issue by Pilad** [GlodBlock/AE2FluidCraft-Rework#5]
If you play without extra cells, then you also need a terminal for filling and emptying the capsules. Fluid import bass is also needed to import/export liquid from machines.

**Comment by GlodBlock** [comment]
the fluid import/export is added with config now, while the fluid terminal is bit troublesome to code.

**Comment by GlodBlock** [comment]
all of these parts have been added in latest ae2fc
