### ISSUE TITLE
Crashes happens when using Set Amount UI

### ISSUE THREAD

**Issue by YiRanMushroom** [GlodBlock/AE2FluidCraft-Rework#50]
You have already add a UI that can set the amount of item/fluid and it can basically works in most cases.
But sometimes when clinking the Set button, it will crash the game. And when joining back to the game, texture failures could occur(Including Missing Skin textures, and some rendering failures, especially in the AE2 UI)
I also found that before the failure happens, the Set operation could be very lagging,but after it crashes(with texture failures), the function works perfectly.
Here are some images.
![image](https://user-images.githubusercontent.com/114495322/194768977-00afa985-81f0-4885-9b5c-18f1e4f8d470.png)
![image](https://user-images.githubusercontent.com/114495322/194768995-83e49c2c-50c6-43b2-b011-dc5a4ba0b3b9.png)

**Comment by GlodBlock** [comment]
could you provide the crash report or the client log?

**Comment by YiRanMushroom** [comment]
[crash-2022-10-11_18.31.41-server.txt](https://github.com/GlodBlock/AE2FluidCraft-Rework/files/9754719/crash-2022-10-11_18.31.41-server.txt)
I am not sure if this is the right one but I think it is.
(I have read this but I think this crash report cant help with analysing the problem.So I didnt send it.)

**Comment by GlodBlock** [comment]
it looks like an unrelated crash.
if you meet with this bug again, plz send me the crash report and logs

**Comment by YiRanMushroom** [comment]
I think i have already figured out the reason, it should be basically caused by another mod not enough energistics. (But i am not sure, I just disabled some functions of that mod and it seemed that this problem have already beed fixed because of that.)
And I also found a new problem, and I am going to post a new issue about it.

**Comment by GlodBlock** [comment]
what function you disabled in nee? i don't think nee may tweaker anything related to ae2fc

**Comment by YiRanMushroom** [comment]
Sorry, i was proved wrong, it just crashes randomly even after I disabled those functions of NEE.
But I do think this crash has something to do with the "auto switch pattern terminal mode" function of NEE, or AE2 unofficial extended life.

**Comment by GlodBlock** [comment]
do you have the crash report?

**Comment by YiRanMushroom** [comment]
I think it was not automatically generated, I could not found any related crash report in the folder crash-reports.
BTW, it should be a problem happening on the server, cuz when it was happening, this appeared no my screen.
![QQ截图20221013201540](https://user-images.githubusercontent.com/114495322/195593718-9070d92c-2949-4fd2-8ab0-9b3ba9862b2a.png)
![QQ截图20221013201706](https://user-images.githubusercontent.com/114495322/195593819-d0a5eb11-fa8d-4cae-b0a5-0cd827e9b058.png)

**Comment by GlodBlock** [comment]
then send me the latest client log, you should be able to find it in log folder

**Comment by YiRanMushroom** [comment]
I dont know which one I should send so Iam gonna send these two files, I think it could be helpful.
[debug.log](https://github.com/GlodBlock/AE2FluidCraft-Rework/files/9776612/debug.log)
[latest.log](https://github.com/GlodBlock/AE2FluidCraft-Rework/files/9776614/latest.log)

**Comment by GlodBlock** [comment]
ok, i see the problem. hopefully it can be fixed soon

**Comment by GlodBlock** [comment]
try this https://github.com/GlodBlock/AE2FluidCraft-Rework/releases/tag/2.4.2-r
