### ISSUE TITLE
Subtle problems when making a pattern.

### ISSUE THREAD

**Issue by YiRanMushroom** [GlodBlock/AE2FluidCraft-Rework#51]
The amount of item in a slot of a pattern can not be too big (less than 127).
Or the amount would become -128 and the pattern becomes "Invalid".
![QQ截图20221013002854](https://user-images.githubusercontent.com/114495322/195398756-293e9a69-98cf-41e6-85e3-dc87bb34c01e.png)

**Comment by GlodBlock** [comment]
it is an ae2 side problem and @PrototypeTrousers has fixed it in https://github.com/PrototypeTrousers/Applied-Energistics-2/commit/9ac4ea4e6eaf37b3476b531d294c7f8765c7e9f9 , just wait him release the latest
