### ISSUE TITLE
建议：液体液滴在me终端中的显示

### ISSUE THREAD

**Issue by yang-fu** [GlodBlock/AE2FluidCraft-Rework#55]
在me终端里，处于合成中的液滴数量在不停变化，而且由于通常都是几千mb或者消耗殆尽然后又产生新的液体，导致物品排列顺序不断变化，能否想办法让me终端里可以不显示液滴数量？
例如显示元件可以正则表达？

**Comment by GlodBlock** [comment]
我记得1.7的显示元件可以加模糊卡，你看看1.12的可不可以

**Comment by yang-fu** [comment]
加了模糊卡和反向卡就行了  谢谢
