### ISSUE TITLE
ME二合一接口UI错位

### ISSUE THREAD

**Issue by EtaCarina** [GlodBlock/AE2FluidCraft-Rework#56]
![2022-10-21_22 13 58](https://user-images.githubusercontent.com/20508876/197219603-369222d9-c16e-445a-a3bb-5ef62ceb13c7.png)
![2022-10-21_22 24 09](https://user-images.githubusercontent.com/20508876/197219625-d0ac3a72-a0f8-4d8a-a3a3-cc3103d75262.png)
ME二合一接口UI错位

**Comment by GlodBlock** [comment]
材质包问题，它材质还是适配的官方ae
