### ISSUE TITLE
Fluid input for normal crafts

### ISSUE THREAD

**Issue by adamcirillo** [GlodBlock/AE2FluidCraft-Rework#57]
Can you add fluid crafting in normal crafts like for eg crafting a cobblestone gen requires water and lava bucket and replace it with liquid. I figure you have to write a new assembler block for this.

**Comment by Xikaro** [comment]
you can do the same with craft tweaker

**Comment by Xikaro** [comment]
or use other blocks used for this, for example, in Gregtech there is such a block

**Comment by GlodBlock** [comment]
added in [2.4.9-r](https://github.com/GlodBlock/AE2FluidCraft-Rework/releases/tag/2.4.9-r)
