### ISSUE TITLE
Latest AE2 Unofficial Alpha breaks reflection hacks

### ISSUE THREAD

**Issue by brisingraerowing** [GlodBlock/AE2FluidCraft-Rework#58]
[Crash Log](https://gist.github.com/brisingraerowing/d10233dc190290f7dd30036efd4c96c8)

**Comment by GlodBlock** [comment]
please use the latest ae2fc https://www.curseforge.com/minecraft/mc-mods/ae2-fluid-crafting-rework/files/4035319
