### ISSUE TITLE
使用子网络时，流体自动合成发送的液体数量与配方不符

### ISSUE THREAD

**Issue by yang-fu** [GlodBlock/AE2FluidCraft-Rework#59]
这个配方是
16B的石脑油
2B的炼油气
1B的甲醇
1B的丙酮
 合成得到 20B的粗汽油

如果使用ME接口和ME接口板连接，再使用流体存储总线输出液体，在自动合成时，液体发送的数量会有误，换不同容器 ，结果一样

me接口设置为发送真实流体

![98c6e5bad01d2a0117cc76364c004e3](https://user-images.githubusercontent.com/66714394/198823334-b94455af-90ff-4165-8bc1-1e67b1b9e172.jpg)
石脑油会发送40B   其余正常

AE版本
appliedenergistics2-rv6-stable-7-extended_life-v0.54.8.jar

ae2fc  2.4.3

**Comment by yang-fu** [comment]
当把配方中石脑油的数量逐步减少到4B时，发送数量正常，其余配方在液体数量超过4B时均有这个问题，正常使用me接口  不使用子网络则没有这个问题

**Comment by GlodBlock** [comment]
ae2的问题，已提交修复

**Comment by GlodBlock** [comment]
更新ae2 https://www.curseforge.com/minecraft/mc-mods/ae2-extended-life/files/4056418
