### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by RedShiftT** [GlodBlock/AE2FluidCraft-Rework#6]
Server can't load with this mod, it throws an exception. 

Here is console log: https://pastebin.com/sGhhgUqi
And crash log: https://pastebin.com/y5EC4aqK

**Comment by GlodBlock** [comment]
try this https://github.com/GlodBlock/AE2FluidCraft-Rework/releases/tag/gb2aee3c

**Comment by RedShiftT** [comment]
It started correctly, thanks for the quick respond.
