### ISSUE TITLE
液体配方样板编码时不方便

### ISSUE THREAD

**Issue by yang-fu** [GlodBlock/AE2FluidCraft-Rework#60]
当使用jei添加配方时，配方种会以流体形式显示，这时只能鼠标右键每次减少1000mb  没有其他编辑办法
<img width="413" alt="image" src="https://user-images.githubusercontent.com/66714394/198824276-d0da7b63-7034-431b-96ee-ffc40bc27093.png">
<img width="426" alt="image" src="https://user-images.githubusercontent.com/66714394/198824284-71cc53d2-1d5c-49d9-b87a-3024022cb2c9.png">

**Comment by GlodBlock** [comment]
使用装有该流体的容器右键可以增加流体量。
或者使用鼠标中键，直接打开数量修改界面：
![image](https://user-images.githubusercontent.com/60341015/198828095-ae58863a-3e0a-4148-92c6-42e4e8942dcf.png)

**Comment by yang-fu** [comment]
好的 谢谢
