### ISSUE TITLE
Add extra upgrade slot for ME dual interface

### ISSUE THREAD

**Issue by YiRanMushroom** [GlodBlock/AE2FluidCraft-Rework#61]
After the update of PAE2 fuild interfaces can be equiped two capacity card, which means up to 6 upgrade slots are needed in dual interface.
So in order to equip those upgrades, two more extra slots are needed.

**Comment by GlodBlock** [comment]
well it seems bit troublesome to deal with. i can't promise when i can fix it

**Comment by GlodBlock** [comment]
fixed in https://github.com/GlodBlock/AE2FluidCraft-Rework/releases/tag/2.4.12-r
