### ISSUE TITLE
Dual Interface fluid crafting GTECU Multiblocks unable to craft

### ISSUE THREAD

**Issue by adamcirillo** [GlodBlock/AE2FluidCraft-Rework#62]
Trying to do fluid crafting on GTECU Multiblocks the interface will not push the items and the fluids to the machine. Have trying using a tungsten steel pipe and enderio ender fluid conduits run into the same problem. Here is a screenshot of my setup. also using MV Input bus and Hatch if that matters.

using Nomifactory 1.4.1 with AE2FCRework 2.3.4 and also 2.4.1.

![image](https://user-images.githubusercontent.com/13363284/200097867-29f86330-42b3-43ce-b4c0-b58990dd0722.png)

**Comment by GlodBlock** [comment]
fixed in https://github.com/GlodBlock/AE2FluidCraft-Rework/releases/tag/2.4.5-r

**Comment by adamcirillo** [comment]
I've tried this out since i updated nomifactory to 1.4.2 they had the update ae2extendedlife in it i can't seem to get and fluid out the dual interface at all and this setup here that i used with the buffers would not output any liquid worked fine. i reverted to 2.4.4 and it went back to working how it was before. 
![image](https://user-images.githubusercontent.com/13363284/201459938-008fb0b0-59d9-4256-a43b-0fe385c88713.png)

**Comment by GlodBlock** [comment]
you mean the dual interface can't output fluid when request crafting jobs or its fluid buffer can't be extracted?

**Comment by GlodBlock** [comment]
@adamcirillo try this one https://github.com/GlodBlock/AE2FluidCraft-Rework/releases/tag/2.4.6-r

**Comment by adamcirillo** [comment]
that fixed the buffers the original issue was when requesting auto crafting it would not insert the fluid into the hatch the items ended up in the bus. Also the setup in my 1st post works now it puts the liquid into the hatch with the auto crafting recipe.
