### ISSUE TITLE
Dual interface stops blocking if pattern contains only fluids

### ISSUE THREAD

**Issue by Ydrec** [GlodBlock/AE2FluidCraft-Rework#63]
Tested on versions 1.0.22-gtnh which comes with gtnh 2.2.3 and 1.0.31-gtnh

Dual interface ignores blocking mode if requested pattern doesn't have an item as one of input resources.
This was tested with many different tanks and recipe buffer from ae2fc itself

**Comment by GlodBlock** [comment]
fixed in latest
