### ISSUE TITLE
Manually placing fluid in a pattern bugged

### ISSUE THREAD

**Issue by Ydrec** [GlodBlock/AE2FluidCraft-Rework#64]
Tested on versions 1.0.22-gtnh which comes with gtnh 2.2.3 and 1.0.31-gtnh

In fluid pattern terminal to encode a fluid manually in a pattern you need to hold LMB and swipe with fluid container over 2+ slots for it to turn into fluid packet. Placing fluid container with any button combination in a single slot just places it as an item.

**Comment by GlodBlock** [comment]
that is neiaddon's issue, use the latest from jenkins http://jenkins.usrv.eu:8080/job/Neiaddons/29/

**Comment by Ydrec** [comment]
replacing that jar fixed it. Now it can be placed properly with middle mouse button, bit unintuitive but fixed. Thanks
