### ISSUE TITLE
二合一接口缺少给OC的流体控制相关api

### ISSUE THREAD

**Issue by wumingzhiren** [GlodBlock/AE2FluidCraft-Rework#65]
隔壁EC2有setFluidInterfaceConfiguration和setFluidInterfaceConfiguration两种方法，希望能加上以方便装配线自动化

**Comment by asdflj** [comment]
有可以不需要OC的方法啊

**Comment by wumingzhiren** [comment]
> 有可以不需要OC的方法啊
其他方法有的是，但我还真没见过能像我这个一套装配线和一套装置直接包打天下的
请不要轻易否定其他方法，特别是不了解的情况下

**Comment by GlodBlock** [comment]
已添加
