### ISSUE TITLE
Make All fluids dragable in a pattern terminal.

### ISSUE THREAD

**Issue by YiRanMushroom** [GlodBlock/AE2FluidCraft-Rework#66]
When making patterns with fluids, some fluids could be dragged through JEI. However, this need special adapting of the mod.
In this case, thermal expansion fluids are dragable.
![image](https://user-images.githubusercontent.com/114495322/202182070-a43070d7-7eff-46ab-bc2c-9b39ac30d613.png)
But content tweaker ones are not.
![image](https://user-images.githubusercontent.com/114495322/202182244-b4874f4c-8d33-4bb5-9375-24225a5e93db.png)

**Comment by asdflj** [comment]
![image](https://user-images.githubusercontent.com/33802162/202494325-2e381699-7b6b-462d-bb23-ea0e429a33a9.png)

**Comment by GlodBlock** [comment]
看起来像是jei和ct的兼容性问题

**Comment by YiRanMushroom** [comment]
I dont think so. Because many mods have the problem and fluids from few mods are dragable.

**Comment by YiRanMushroom** [comment]
And I think make each fluid packet to be displayed in jei could easyly sovle this problem.
like this:
![image](https://user-images.githubusercontent.com/114495322/202853231-16ad6410-7329-4474-9d8d-a37a58e64768.png)

**Comment by asdflj** [comment]
你俩在嘎哈呢
还好我不玩失重

**Comment by GlodBlock** [comment]
added in [2.4.10-r](https://github.com/GlodBlock/AE2FluidCraft-Rework/releases/tag/2.4.10-r)
