### ISSUE TITLE
Crash when opening fluid pattern terminal

### ISSUE THREAD

**Issue by Xikaro** [GlodBlock/AE2FluidCraft-Rework#67]
[crash-2022-11-21_22.41.45-server.txt](https://github.com/GlodBlock/AE2FluidCraft-Rework/files/10059188/crash-2022-11-21_22.41.45-server.txt)

Fluid Craft for AE2-2.4.7-r.jar
appliedenergistics2-rv6-stable-7-extended_life-v0.54.13.jar
HadEnoughItems_1.12.2-4.24.1.jar

**Comment by GlodBlock** [comment]
fixed in 2.4.8 https://github.com/GlodBlock/AE2FluidCraft-Rework/releases
