### ISSUE TITLE
Server crash on craft

### ISSUE THREAD

**Issue by RedShiftT** [GlodBlock/AE2FluidCraft-Rework#7]
The server started correctly first time, but died after I ordered fluid interface from ae2 autocrafting.

Death crash log: https://pastebin.com/Wr5KGXQP

After that server can't start anymore. Don't worry if mod broke minecraft world, I have backup.
crash log: https://pastebin.com/K029DjwC
server console log: https://controlc.com/4900a85a 
(sorry can't load it to pastebin due to their ""SMART filters"")

**Comment by RedShiftT** [comment]
Found out that it crashes whenever I try to order smth, even items from other mods and different machines.

Recorded console log if you need: https://controlc.com/baf63b8c

In singleplayer autocrafting works properly.

**Comment by Pilad** [comment]
> Found out that it crashes whenever I try to order smth, even items from other mods and different machines.
> 
> Recorded console log if you need: https://controlc.com/baf63b8c
> 
> In singleplayer autocrafting works properly.

Use new version https://github.com/GlodBlock/AE2FluidCraft-Rework/releases

**Comment by GlodBlock** [comment]
yeah that release should fix the server crash.

**Comment by RedShiftT** [comment]
Thanks for fix, it works now!
