### ISSUE TITLE
Autofill problems with pattern terminal

### ISSUE THREAD

**Issue by YiRanMushroom** [GlodBlock/AE2FluidCraft-Rework#80]
Make pattern terminal search the ME system so that it can automatically fill the existing item in the system when use jei auto fill.(The PAE2 has already changed like this)

**Comment by asdflj** [comment]
added in gtnh version https://github.com/GTNewHorizons/AE2FluidCraft-Rework/pull/72/files

**Comment by GlodBlock** [comment]
> added in gtnh version https://github.com/GTNewHorizons/AE2FluidCraft-Rework/pull/72/files

他说的是jei自动填充

**Comment by asdflj** [comment]
啊,我还以为用他说错了呢,用nei填充的时候自动用AE库存里面的物品

**Comment by asdflj** [comment]
这里居然有非gtnh的

**Comment by GlodBlock** [comment]
这里大部分是1.12的

**Comment by GlodBlock** [comment]
added by https://github.com/GlodBlock/AE2FluidCraft-Rework/commit/871c73324508d1ffb84d4d8922763c3f1acb50ad
