### ISSUE TITLE
需要兼容最新PAE2

### ISSUE THREAD

**Issue by magcicada** [GlodBlock/AE2FluidCraft-Rework#81]
PAE2修改了物品堆叠方式，在堆叠的core mod上会抛出NoSuchMethodError然后崩溃。
崩溃报告指出是
https://github.com/GlodBlock/AE2FluidCraft-Rework/blob/1.12.2/src/main/java/com/glodblock/github/coremod/CoreModHooks.java#L135

**Comment by magcicada** [comment]
我的是AE的开发环境，崩溃报告你在正常环境也能得到，一试便知...CR就不给你了

**Comment by GlodBlock** [comment]
jei/hei版本多少

**Comment by GlodBlock** [comment]
我这里测试了最新的pae2和ae2fc，并没有发生崩溃。你发的那行是jei相关的东西，所以你最好还是把原始报告发给我

**Comment by asdflj** [comment]
![CSV@L3ENAHI5RHN}Z@ 8KY8](https://user-images.githubusercontent.com/33802162/215312931-de3cda2e-42b6-448e-b76a-fc2a6a8207bc.gif)

**Comment by magcicada** [comment]
PAE2开发环境中的JEI..

**Comment by magcicada** [comment]
我先脱离开发环境试试

**Comment by magcicada** [comment]
好吧，我把JEI升级到了最新的HEI就不会发生这种崩溃了....
