### ISSUE TITLE
Item conduit inconsistency with dual interface behavior vs normal interface

### ISSUE THREAD

**Issue by Ydrec** [GlodBlock/AE2FluidCraft-Rework#85]
Version: 1.0.67-gtnh

Dual interface in blocking mode considers item conduits as always empty and always sends items thru them even when in blocking mode.
Normal interfaces don't send items in them when in blocking mode, or consider them to be blocked. 

Normal interface behavior allows to output items to conduits only if there wasn't enough space in another proper inventory.

That for example allowed to automate placing items in Assembly line when bus directly connected to interface emptied and allowed 1 item with the rest send to conduits and placed in order without any further settings.

Dual interface current behavior makes using item conduits with blocking mode borderline impossible

Suggestion: Make dual interface not do a blocking check on conduits in blocking mode while allowing to output if there is no blocking mode or the recipe is already cached in interface to be outputted.

I understand this change request may not attract enough attention and thus not be implemented.
I believe this feature would make the mod better.

**Comment by YiRanMushroom** [comment]
You are using what conduit? And I don't know what you mean in the suggestion, you mean the dual interface should do a blocking check to the conduit when in blocking mode, right?

Also the project is mainly for the 1.12.2 version, I think you should find another place to post if you are playing the 1.7.10 version.
