### ISSUE TITLE
Add more blocking mode settings.

### ISSUE THREAD

**Issue by YiRanMushroom** [GlodBlock/AE2FluidCraft-Rework#86]
When using ae2 with ae2fc installed, both the normal and the dual interface would block ingredients when there are fluids in the machine, which is inconvenient in some cases, such as automating the blood altar.

Here are some suggestions:
1.You can make normal interface not to block ingredients when fluids are in the machine while the dual interface block ingredients when fluids are in.
2.You can make the ingredients only to be blocked if the recipe has fluids in it.
3.You can add a setting in the interface that allows more blocking modes, such as only blocking items, blocking items and fluids, or sent the next set of ingredients when receiving a redstone pause (like the crafting chamber of rs in 1.16.4).

The first one or two seems to be easier, however the problem is not fatal and may not need to be resolved since other methods can be used to control the import ingredients. But if you can solve it by using the third method, it would be really wholesome.

**Comment by Ydrec** [comment]
There are multiple setups to allow this behavior using subnets/p2p/conduits. Main problem seems to be normal interface being blocked by fluids.

**Comment by Ydrec** [comment]
Checked, doesn't happen in 1.7.10 branch with gtnh ae fork. Normal interface ignores fluid in inventory when using blocking mode

**Comment by YiRanMushroom** [comment]
It happens in 1.12.2, and I of course could be handled in many ways, I just give some suggestions.

**Comment by jk1895** [comment]
Hello,
can you please fix this? Your mod prevents blocking mode from working properly when there are fluids in the machine.
This is very unfortunate.

**Comment by GlodBlock** [comment]
it isn't that easy to fix and i don't have much spare time recently

**Comment by jk1895** [comment]
Thank you for your quick response. Maybe you could ask PrototypeTrousers for help then? He is a genius and might know a simpler solution? I hope you know who I mean.
Nevertheless, thank you very much.

**Comment by GlodBlock** [comment]
added in [2.4.20-r](https://github.com/GlodBlock/AE2FluidCraft-Rework/releases/tag/2.4.20-r)

**Comment by jk1895** [comment]
> added in [2.4.20-r](https://github.com/GlodBlock/AE2FluidCraft-Rework/releases/tag/2.4.20-r)

Thanks for your attempt to fix the problem.
Unfortunately, the interface still sees the fluids as " items" when you turn on blocking mode.  No matter what setting I choose now (ignore only fluids, only items, or both), the interface will not let any items into the machine if there is only one drop of a fluid in it.

**Comment by GlodBlock** [comment]
eh, can you try this
[Fluid Craft for AE2-2.4.20-r.zip](https://github.com/GlodBlock/AE2FluidCraft-Rework/files/11584690/Fluid.Craft.for.AE2-2.4.20-r.zip)
unzip it to use

**Comment by jk1895** [comment]
YES, with this JAR it now works like a charm! I have tried all modes and
the new blocking mode seems to work fine.
I tried it on GTCEu on a chemical reactor and a circuit assembler.
Thank you very much!
