### ISSUE TITLE
Pattern Capacity Card in Fluid Interfaces

### ISSUE THREAD

**Issue by RedShiftT** [GlodBlock/AE2FluidCraft-Rework#9]
There are slots for upgrade cards and dark slots for patterns but I can't insert neither advanced nor basic cap. card. 

Will they work or this interfaces supposed to be limited like extracells2 ones?

**Comment by GlodBlock** [comment]
oops, i just fixed card bug for 1.12.2 version yesterday, forget the 1.7.10 interfaces

**Comment by GlodBlock** [comment]
https://github.com/GlodBlock/AE2FluidCraft-Rework/releases/tag/g6061dc8

**Comment by RedShiftT** [comment]
Cards work now, thanks a lot for your job!

**Comment by GlodBlock** [comment]
btw, are you using the gtnh edition ae2? because official ae2 doesn't support pattern capacity cards

**Comment by RedShiftT** [comment]
I'm not sure what version is it but I play another GT5U modpack. It could be same ae2 as gtnh have
[appliedenergistics2-rv3-ii-edition-1.18.0_12.zip](https://github.com/GlodBlock/AE2FluidCraft-Rework/files/8748086/appliedenergistics2-rv3-ii-edition-1.18.0_12.zip)
