### ISSUE TITLE
Crash: java.lang.NullPointerException

### ISSUE THREAD

**Issue by 123FLO321** [GlodBlock/AE2FluidCraft-Rework#91]
Random crashes with NullPointerException.

See crash report:
[crash-2023-03-29_15.38.18-server.txt](https://github.com/GlodBlock/AE2FluidCraft-Rework/files/11104785/crash-2023-03-29_15.38.18-server.txt)

**Comment by GlodBlock** [comment]
when this crash happens? request crafting jobs or just randomly crushes?

**Comment by 123FLO321** [comment]
It happened when canceling a crafting

**Comment by GlodBlock** [comment]
well i can't reproduce the crash. could you give me screenshot of which crafting job you are canceling?

**Comment by PrototypeTrousers** [comment]
Looks like Plethora can interact with AE from another thread. Not sure how to go about that

**Comment by 123FLO321** [comment]
It should always use the main thread unless `worldThread = false` is specified in the `@PlethoraMethod` decorator. 
All interactions should be performed from the main thread unless I missed something (I also debugged the craft method and it is in fact called from the server thread)

**Comment by 123FLO321** [comment]
Posted on AE as well since it's probably unrelated to AE2FC: https://github.com/PrototypeTrousers/Applied-Energistics-2/issues/255

**Comment by 123FLO321** [comment]
see : https://github.com/PrototypeTrousers/Applied-Energistics-2/issues/255
