### ISSUE TITLE
待机时间久了服务器tps暴跌，看起来是与eio的共同作用

### ISSUE THREAD

**Issue by KuroPeach** [GlodBlock/AE2FluidCraft-Rework#92]
待机时间久了服务器tps暴跌，看起来是与eio的共同作用
[sampler-snapshot_0.zip](https://github.com/GlodBlock/AE2FluidCraft-Rework/files/11187381/sampler-snapshot_0.zip)
![{EL4A` }K%G8O$(SMHWTY$2](https://user-images.githubusercontent.com/19620848/230819213-4f22f923-1dac-49a7-89b4-756b08b2f985.png)

**Comment by GlodBlock** [comment]
1.7的我已经停止开发了，你直接去nh那边发issue吧

**Comment by KuroPeach** [comment]
啊这，那我让他们把eio的me管子全撤了得了
