### ISSUE TITLE
Crash on ordering recipes with 9+ components

### ISSUE THREAD

**Issue by BortEngineerDude** [GlodBlock/AE2FluidCraft-Rework#93]
If processing pattern recipe takes more than 9 slots, attempt to execute crafting will result in crash.
[crash-2023-04-16_23.22.23-server.txt](https://github.com/GlodBlock/AE2FluidCraft-Rework/files/11244700/crash-2023-04-16_23.22.23-server.txt)

**Comment by GlodBlock** [comment]
sadly the 1.7 version is no longer supported here. but i suggest you to use gtnh's ae2 instead of the official ae2

**Comment by BortEngineerDude** [comment]
Seems like it works, yeah. Probably, it's better to mention it somewhere on the description page.
