### ISSUE TITLE
Memory card cannot copy patterns on dual interfaces

### ISSUE THREAD

**Issue by JonasRothSwinx** [GlodBlock/AE2FluidCraft-Rework#95]
On regular interfaces, you can use the memory card to copy/paste patterns from one interface into another, provided you have blank patterns in your inventory.
Trying to do the same thing to copy from one dual interface to another does only copy the interface settings, but not the patterns. Can that functionality be extended to dual interfaces please?

**Comment by GlodBlock** [comment]
fixed in 2.4.19-r

**Comment by CheatingChicken** [comment]
Little Follow-up to this:
Thee memory card now successfully copies the settings. One remaining problem is, any encoded fluids only start getting stocked, when you manually change anything about the fluid interface part of the dual interface. I assume something isn't getting updated on pasting the settings?

**Comment by GlodBlock** [comment]
@CheatingChicken fixed in 2.4.22-r
also please post a new issue if you find something wrong, sometimes i can't notice the comment
