### ISSUE TITLE
[Proposal] P2P Tunnel - ME Dual Interface

### ISSUE THREAD

**Issue by 5lx** [GlodBlock/AE2FluidCraft-Rework#96]
Hi,

I'm playing GTNH v2.3.0 and found there's a new ME Interface version of P2P tunnel got introduced.
This saved lot of my time to config multi interfaces, and we don't need to place dup patterns into the interfaces.
Could we also have an ME Dual Interface version of P2P tunnel?

Thank you!

**Comment by GlodBlock** [comment]
you should send this suggestion to gtnh's repo: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues

**Comment by GlodBlock** [comment]
they have been added now
