### ISSUE TITLE
Dual Interface GUI problem and solution

### ISSUE THREAD

**Issue by ghost** [GlodBlock/AE2FluidCraft-Rework#97]
The Dual Interface has a problem with its background. Just delete 

    @Override
    protected String getBackground() {
        return "guis/interface.png";}

in GuiItemDualInterface.java and it works again flawlessly.

**Comment by GlodBlock** [comment]
![image](https://github.com/GlodBlock/AE2FluidCraft-Rework/assets/60341015/351da88a-df4f-4e9d-b9c2-2007b4e18dc7)
the gui looks fine to me

**Comment by GlodBlock** [comment]
well i see what you mean
fixed in 2.4.23-r
