### ISSUE TITLE
AE2 crafting bytes calculations inaccurate for uncraftable fluids

### ISSUE THREAD

**Issue by chloecat34** [GlodBlock/AE2FluidCraft-Rework#99]
When requesting a craft that involves craftable fluids, AE2 seems to produce the correct results (treating 1000 mb of the fluid as 1 byte). However, whenever the fluids used in the craft are not craftable, they are treated as 1 byte per mb (so 1000 mb becomes 1000 bytes). So if a craft used 144 mb of Molten Iron, if the Molten Iron had a pattern then it would use 1 byte to represent it, but if it didn't then it would use 144 bytes. This doesn't seem intended.

Testing was done on 1.12 with AE2 Unofficial Extended Life.

**Comment by GlodBlock** [comment]
fixed in 2.4.24
